apiVersion: v1
kind: Service
metadata:
  name: digital-channels-gateway-svc
  namespace: ccaas-dev
  labels:
    app: digital-channels-gateway
spec:
  selector:
    app: digital-channels-gateway
  ports:
    - name: grpc
      port: 50053
      targetPort: 50053
