apiVersion: v1
kind: Service
metadata:
  name: api-gateway-svc
  namespace: ccaas-dev
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
    - name: grpc
      port: 50059
      targetPort: 50059
