// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: presence/v1/presence.proto

package presencev1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// PresenceServiceClient is the client API for PresenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PresenceService is owned by the Agent & Presence service (architecture doc
// Section 2.2). Its actual scope (per the milestone that implemented the
// live WebSocket connection registry) is: hold the live WebSocket
// connection to every logged-in Agent Desktop, relay a filtered subset of
// Task Router's domain events to the agent each connection belongs to, and
// nothing else -- it does NOT duplicate Task Router's Agent entity
// (status, capacity, queues), and Task Router never calls into this
// service synchronously (Task Router already owns all agent routing state
// it needs internally).
//
// The service definition below is intentionally left empty. It is kept
// (rather than deleting the file / package) so the package structure,
// generated Go package, and buf module entry stay stable for a future
// RPC -- e.g. an internal "IsAgentConnected(agentId) -> bool" query
// another service might want -- without a breaking rename. Nothing in the
// current milestone's scope needs a synchronous RPC into this service: the
// only client-facing surface is the WebSocket upgrade endpoint (see
// services/agent-presence/README.md), which is plain HTTP, not gRPC. The
// gRPC server this service still runs is registered for the standard
// health check only (see pkg/health).
//
// The previously-defined GetAvailableAgents RPC (and its Request/Response/
// Agent messages) has been removed: Task Router never called it, and it
// duplicated state that Task Router already owns as the sole source of
// truth for agent routing eligibility.
type PresenceServiceClient interface {
}

type presenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPresenceServiceClient(cc grpc.ClientConnInterface) PresenceServiceClient {
	return &presenceServiceClient{cc}
}

// PresenceServiceServer is the server API for PresenceService service.
// All implementations must embed UnimplementedPresenceServiceServer
// for forward compatibility.
//
// PresenceService is owned by the Agent & Presence service (architecture doc
// Section 2.2). Its actual scope (per the milestone that implemented the
// live WebSocket connection registry) is: hold the live WebSocket
// connection to every logged-in Agent Desktop, relay a filtered subset of
// Task Router's domain events to the agent each connection belongs to, and
// nothing else -- it does NOT duplicate Task Router's Agent entity
// (status, capacity, queues), and Task Router never calls into this
// service synchronously (Task Router already owns all agent routing state
// it needs internally).
//
// The service definition below is intentionally left empty. It is kept
// (rather than deleting the file / package) so the package structure,
// generated Go package, and buf module entry stay stable for a future
// RPC -- e.g. an internal "IsAgentConnected(agentId) -> bool" query
// another service might want -- without a breaking rename. Nothing in the
// current milestone's scope needs a synchronous RPC into this service: the
// only client-facing surface is the WebSocket upgrade endpoint (see
// services/agent-presence/README.md), which is plain HTTP, not gRPC. The
// gRPC server this service still runs is registered for the standard
// health check only (see pkg/health).
//
// The previously-defined GetAvailableAgents RPC (and its Request/Response/
// Agent messages) has been removed: Task Router never called it, and it
// duplicated state that Task Router already owns as the sole source of
// truth for agent routing eligibility.
type PresenceServiceServer interface {
	mustEmbedUnimplementedPresenceServiceServer()
}

// UnimplementedPresenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPresenceServiceServer struct{}

func (UnimplementedPresenceServiceServer) mustEmbedUnimplementedPresenceServiceServer() {}
func (UnimplementedPresenceServiceServer) testEmbeddedByValue()                         {}

// UnsafePresenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PresenceServiceServer will
// result in compilation errors.
type UnsafePresenceServiceServer interface {
	mustEmbedUnimplementedPresenceServiceServer()
}

func RegisterPresenceServiceServer(s grpc.ServiceRegistrar, srv PresenceServiceServer) {
	// If the following call panics, it indicates UnimplementedPresenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PresenceService_ServiceDesc, srv)
}

// PresenceService_ServiceDesc is the grpc.ServiceDesc for PresenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PresenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "presence.v1.PresenceService",
	HandlerType: (*PresenceServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "presence/v1/presence.proto",
}
