// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: presence/v1/presence.proto

package presencev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PresenceService_GetAvailableAgents_FullMethodName = "/presence.v1.PresenceService/GetAvailableAgents"
)

// PresenceServiceClient is the client API for PresenceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PresenceService is owned by the Agent & Presence service (architecture doc
// Section 2.2) and is the synchronous gRPC contract Task Router uses to ask
// "who is available right now" (Section 3.2 IPC summary table).
//
// NOTE: tenant_id is deliberately NOT a field on any message here. Per
// architecture doc Section 1.1, tenant scoping travels as gRPC metadata
// (`x-tenant-id`), injected/validated by the pkg/tenantctx interceptor on
// both the client and server side — never as an in-message field.
type PresenceServiceClient interface {
	// GetAvailableAgents returns the agents currently eligible to receive a
	// task of the given type from the given queue. This is a contract
	// skeleton only — the full eligibility/matching semantics live in the
	// Task Router domain (see TASK_ROUTER_SPECIFICATION.md) and are not
	// implemented by this scaffold.
	GetAvailableAgents(ctx context.Context, in *GetAvailableAgentsRequest, opts ...grpc.CallOption) (*GetAvailableAgentsResponse, error)
}

type presenceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPresenceServiceClient(cc grpc.ClientConnInterface) PresenceServiceClient {
	return &presenceServiceClient{cc}
}

func (c *presenceServiceClient) GetAvailableAgents(ctx context.Context, in *GetAvailableAgentsRequest, opts ...grpc.CallOption) (*GetAvailableAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableAgentsResponse)
	err := c.cc.Invoke(ctx, PresenceService_GetAvailableAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PresenceServiceServer is the server API for PresenceService service.
// All implementations must embed UnimplementedPresenceServiceServer
// for forward compatibility.
//
// PresenceService is owned by the Agent & Presence service (architecture doc
// Section 2.2) and is the synchronous gRPC contract Task Router uses to ask
// "who is available right now" (Section 3.2 IPC summary table).
//
// NOTE: tenant_id is deliberately NOT a field on any message here. Per
// architecture doc Section 1.1, tenant scoping travels as gRPC metadata
// (`x-tenant-id`), injected/validated by the pkg/tenantctx interceptor on
// both the client and server side — never as an in-message field.
type PresenceServiceServer interface {
	// GetAvailableAgents returns the agents currently eligible to receive a
	// task of the given type from the given queue. This is a contract
	// skeleton only — the full eligibility/matching semantics live in the
	// Task Router domain (see TASK_ROUTER_SPECIFICATION.md) and are not
	// implemented by this scaffold.
	GetAvailableAgents(context.Context, *GetAvailableAgentsRequest) (*GetAvailableAgentsResponse, error)
	mustEmbedUnimplementedPresenceServiceServer()
}

// UnimplementedPresenceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPresenceServiceServer struct{}

func (UnimplementedPresenceServiceServer) GetAvailableAgents(context.Context, *GetAvailableAgentsRequest) (*GetAvailableAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableAgents not implemented")
}
func (UnimplementedPresenceServiceServer) mustEmbedUnimplementedPresenceServiceServer() {}
func (UnimplementedPresenceServiceServer) testEmbeddedByValue()                         {}

// UnsafePresenceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PresenceServiceServer will
// result in compilation errors.
type UnsafePresenceServiceServer interface {
	mustEmbedUnimplementedPresenceServiceServer()
}

func RegisterPresenceServiceServer(s grpc.ServiceRegistrar, srv PresenceServiceServer) {
	// If the following call panics, it indicates UnimplementedPresenceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PresenceService_ServiceDesc, srv)
}

func _PresenceService_GetAvailableAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PresenceServiceServer).GetAvailableAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PresenceService_GetAvailableAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PresenceServiceServer).GetAvailableAgents(ctx, req.(*GetAvailableAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PresenceService_ServiceDesc is the grpc.ServiceDesc for PresenceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PresenceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "presence.v1.PresenceService",
	HandlerType: (*PresenceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAvailableAgents",
			Handler:    _PresenceService_GetAvailableAgents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "presence/v1/presence.proto",
}
