// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: task-router/v1/task_router.proto

package taskrouterv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AttributeValue is the polymorphic numeric|boolean value type used in
// Agent.attributes and Task.required_attributes (spec Sections 2.1, 2.2,
// 2.6). Exactly one field is expected to be set on a valid instance; which
// one is set is compared against the Attribute registry's declared type at
// validation time (spec Section 4.4).
type AttributeValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*AttributeValue_NumberValue
	//	*AttributeValue_BoolValue
	Kind          isAttributeValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeValue) Reset() {
	*x = AttributeValue{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValue) ProtoMessage() {}

func (x *AttributeValue) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValue.ProtoReflect.Descriptor instead.
func (*AttributeValue) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{0}
}

func (x *AttributeValue) GetKind() isAttributeValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *AttributeValue) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*AttributeValue_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *AttributeValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*AttributeValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isAttributeValue_Kind interface {
	isAttributeValue_Kind()
}

type AttributeValue_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,1,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type AttributeValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*AttributeValue_NumberValue) isAttributeValue_Kind() {}

func (*AttributeValue_BoolValue) isAttributeValue_Kind() {}

// ChannelCapacity is one entry in Agent.capacity, keyed by channel/task
// type (spec Section 2.1).
type ChannelCapacity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stored and toggleable, but not read by the matching algorithm (spec
	// Sections 2.1, 5.3, 7.3). Defaults to true.
	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// Maximum concurrent tasks of this channel type. Defaults to 1.
	Max int32 `protobuf:"varint,2,opt,name=max,proto3" json:"max,omitempty"`
	// Current concurrent count. Exclusively managed by the routing system;
	// ignored when supplied by a client on a capacity-update call.
	Active int32 `protobuf:"varint,3,opt,name=active,proto3" json:"active,omitempty"`
	// Stored only, not read anywhere in current logic (spec Section 7.3).
	// Defaults to true.
	Interruptible bool `protobuf:"varint,4,opt,name=interruptible,proto3" json:"interruptible,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelCapacity) Reset() {
	*x = ChannelCapacity{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelCapacity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelCapacity) ProtoMessage() {}

func (x *ChannelCapacity) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelCapacity.ProtoReflect.Descriptor instead.
func (*ChannelCapacity) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{1}
}

func (x *ChannelCapacity) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *ChannelCapacity) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *ChannelCapacity) GetActive() int32 {
	if x != nil {
		return x.Active
	}
	return 0
}

func (x *ChannelCapacity) GetInterruptible() bool {
	if x != nil {
		return x.Interruptible
	}
	return false
}

// Agent mirrors spec Section 2.1, plus one platform-layer addition not in
// the spec: user_id.
type Agent struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	AgentId         string                      `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status          string                      `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Attributes      map[string]*AttributeValue  `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Capacity        map[string]*ChannelCapacity `protobuf:"bytes,4,rep,name=capacity,proto3" json:"capacity,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Queues          []string                    `protobuf:"bytes,5,rep,name=queues,proto3" json:"queues,omitempty"`
	StatusChangedAt *timestamppb.Timestamp      `protobuf:"bytes,6,opt,name=status_changed_at,json=statusChangedAt,proto3" json:"status_changed_at,omitempty"`
	// Optional. The Tenant & Identity Management User ID (proto/tenant-identity/v1)
	// of the human operating this Agent, if known. NOT part of
	// TASK_ROUTER_SPECIFICATION.md's Agent definition -- an explicit,
	// additive link so this Agent's WebSocket connection (Agent & Presence
	// Service, see services/agent-presence/internal/wsserver's doc comment
	// on "Agent identity: reconciling Task Router's Agent with Tenant &
	// Identity's User") can be traced back to a real User record instead of
	// relying solely on an operator's undocumented convention of using the
	// same string for both IDs. Purely informational at this milestone: it
	// is never validated against Tenant & Identity (no cross-service call
	// on the CreateAgent path) and nothing in this service enforces
	// agent_id == user_id for the WebSocket mapping to keep working -- see
	// PROGRESS.md's "Formal Agent <-> User reconciliation" to-do for what a
	// fuller fix would still need to add (validation, and/or using this
	// field instead of agent_id itself for WebSocket routing).
	UserId        string `protobuf:"bytes,7,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{2}
}

func (x *Agent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Agent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Agent) GetAttributes() map[string]*AttributeValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Agent) GetCapacity() map[string]*ChannelCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *Agent) GetQueues() []string {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *Agent) GetStatusChangedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StatusChangedAt
	}
	return nil
}

func (x *Agent) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Task mirrors spec Section 2.2 exactly.
type Task struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	TaskId             string                     `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	QueueId            string                     `protobuf:"bytes,2,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	TaskType           string                     `protobuf:"bytes,3,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	RequiredAttributes map[string]*AttributeValue `protobuf:"bytes,4,rep,name=required_attributes,json=requiredAttributes,proto3" json:"required_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EnqueuedAt         *timestamppb.Timestamp     `protobuf:"bytes,5,opt,name=enqueued_at,json=enqueuedAt,proto3" json:"enqueued_at,omitempty"`
	// One of: "Pending", "Reserved", "Active", "Completed" (spec Section 5.1).
	Status string `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	// The active Offered/Accepted reservation for this task, if any. Empty
	// string means null/none.
	CurrentReservationId string `protobuf:"bytes,7,opt,name=current_reservation_id,json=currentReservationId,proto3" json:"current_reservation_id,omitempty"`
	// Set when matched; cleared when a reservation for this task is
	// rejected; retained (not cleared) once the task completes. Empty
	// string means null/none.
	AssignedAgentId string `protobuf:"bytes,8,opt,name=assigned_agent_id,json=assignedAgentId,proto3" json:"assigned_agent_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{3}
}

func (x *Task) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Task) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

func (x *Task) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *Task) GetRequiredAttributes() map[string]*AttributeValue {
	if x != nil {
		return x.RequiredAttributes
	}
	return nil
}

func (x *Task) GetEnqueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnqueuedAt
	}
	return nil
}

func (x *Task) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Task) GetCurrentReservationId() string {
	if x != nil {
		return x.CurrentReservationId
	}
	return ""
}

func (x *Task) GetAssignedAgentId() string {
	if x != nil {
		return x.AssignedAgentId
	}
	return ""
}

// Reservation mirrors spec Section 2.3 exactly.
type Reservation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	TaskId        string                 `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	AgentId       string                 `protobuf:"bytes,3,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// One of: "Offered", "Accepted", "Rejected" (spec Section 5.2).
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Reservation) Reset() {
	*x = Reservation{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Reservation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reservation) ProtoMessage() {}

func (x *Reservation) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reservation.ProtoReflect.Descriptor instead.
func (*Reservation) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{4}
}

func (x *Reservation) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

func (x *Reservation) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *Reservation) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *Reservation) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Reservation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Reservation) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateAgentRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Unvalidated against the Status registry at creation time (spec
	// Section 3.2). Empty string defaults to "Offline" server-side.
	Status     string                      `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Attributes map[string]*AttributeValue  `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Capacity   map[string]*ChannelCapacity `protobuf:"bytes,4,rep,name=capacity,proto3" json:"capacity,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Queues     []string                    `protobuf:"bytes,5,rep,name=queues,proto3" json:"queues,omitempty"`
	// Optional. See Agent.user_id's doc comment.
	UserId        string `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAgentRequest) Reset() {
	*x = CreateAgentRequest{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAgentRequest) ProtoMessage() {}

func (x *CreateAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAgentRequest.ProtoReflect.Descriptor instead.
func (*CreateAgentRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *CreateAgentRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateAgentRequest) GetAttributes() map[string]*AttributeValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CreateAgentRequest) GetCapacity() map[string]*ChannelCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *CreateAgentRequest) GetQueues() []string {
	if x != nil {
		return x.Queues
	}
	return nil
}

func (x *CreateAgentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{6}
}

type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*Agent               `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{7}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

type GetAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{8}
}

func (x *GetAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type DeleteAgentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAgentRequest) Reset() {
	*x = DeleteAgentRequest{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentRequest) ProtoMessage() {}

func (x *DeleteAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentRequest.ProtoReflect.Descriptor instead.
func (*DeleteAgentRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type DeleteAgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if a Reserved/Active task+reservation was resolved as a side
	// effect of this deletion (spec Section 5.5).
	ResolvedInFlightReservation bool `protobuf:"varint,1,opt,name=resolved_in_flight_reservation,json=resolvedInFlightReservation,proto3" json:"resolved_in_flight_reservation,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *DeleteAgentResponse) Reset() {
	*x = DeleteAgentResponse{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAgentResponse) ProtoMessage() {}

func (x *DeleteAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAgentResponse.ProtoReflect.Descriptor instead.
func (*DeleteAgentResponse) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteAgentResponse) GetResolvedInFlightReservation() bool {
	if x != nil {
		return x.ResolvedInFlightReservation
	}
	return false
}

type SetAgentStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAgentStatusRequest) Reset() {
	*x = SetAgentStatusRequest{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAgentStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAgentStatusRequest) ProtoMessage() {}

func (x *SetAgentStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAgentStatusRequest.ProtoReflect.Descriptor instead.
func (*SetAgentStatusRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{11}
}

func (x *SetAgentStatusRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *SetAgentStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReplaceAgentCapacityRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	AgentId string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Full replacement map. `active` on any entry is ignored server-side.
	Capacity      map[string]*ChannelCapacity `protobuf:"bytes,2,rep,name=capacity,proto3" json:"capacity,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceAgentCapacityRequest) Reset() {
	*x = ReplaceAgentCapacityRequest{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceAgentCapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceAgentCapacityRequest) ProtoMessage() {}

func (x *ReplaceAgentCapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceAgentCapacityRequest.ProtoReflect.Descriptor instead.
func (*ReplaceAgentCapacityRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{12}
}

func (x *ReplaceAgentCapacityRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReplaceAgentCapacityRequest) GetCapacity() map[string]*ChannelCapacity {
	if x != nil {
		return x.Capacity
	}
	return nil
}

type ToggleChannelReadyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Channel       string                 `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Ready         bool                   `protobuf:"varint,3,opt,name=ready,proto3" json:"ready,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleChannelReadyRequest) Reset() {
	*x = ToggleChannelReadyRequest{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleChannelReadyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleChannelReadyRequest) ProtoMessage() {}

func (x *ToggleChannelReadyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleChannelReadyRequest.ProtoReflect.Descriptor instead.
func (*ToggleChannelReadyRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{13}
}

func (x *ToggleChannelReadyRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ToggleChannelReadyRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ToggleChannelReadyRequest) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

type ReplaceAgentQueuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Queues        []string               `protobuf:"bytes,2,rep,name=queues,proto3" json:"queues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceAgentQueuesRequest) Reset() {
	*x = ReplaceAgentQueuesRequest{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceAgentQueuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceAgentQueuesRequest) ProtoMessage() {}

func (x *ReplaceAgentQueuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceAgentQueuesRequest.ProtoReflect.Descriptor instead.
func (*ReplaceAgentQueuesRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{14}
}

func (x *ReplaceAgentQueuesRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReplaceAgentQueuesRequest) GetQueues() []string {
	if x != nil {
		return x.Queues
	}
	return nil
}

type ReplaceAgentAttributesRequest struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	AgentId       string                     `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Attributes    map[string]*AttributeValue `protobuf:"bytes,2,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplaceAgentAttributesRequest) Reset() {
	*x = ReplaceAgentAttributesRequest{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplaceAgentAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplaceAgentAttributesRequest) ProtoMessage() {}

func (x *ReplaceAgentAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplaceAgentAttributesRequest.ProtoReflect.Descriptor instead.
func (*ReplaceAgentAttributesRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{15}
}

func (x *ReplaceAgentAttributesRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ReplaceAgentAttributesRequest) GetAttributes() map[string]*AttributeValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ListAgentPendingOffersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentPendingOffersRequest) Reset() {
	*x = ListAgentPendingOffersRequest{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentPendingOffersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentPendingOffersRequest) ProtoMessage() {}

func (x *ListAgentPendingOffersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentPendingOffersRequest.ProtoReflect.Descriptor instead.
func (*ListAgentPendingOffersRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{16}
}

func (x *ListAgentPendingOffersRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type ListAgentPendingOffersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reservations  []*Reservation         `protobuf:"bytes,1,rep,name=reservations,proto3" json:"reservations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentPendingOffersResponse) Reset() {
	*x = ListAgentPendingOffersResponse{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentPendingOffersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentPendingOffersResponse) ProtoMessage() {}

func (x *ListAgentPendingOffersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentPendingOffersResponse.ProtoReflect.Descriptor instead.
func (*ListAgentPendingOffersResponse) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{17}
}

func (x *ListAgentPendingOffersResponse) GetReservations() []*Reservation {
	if x != nil {
		return x.Reservations
	}
	return nil
}

type EnqueueTaskRequest struct {
	state              protoimpl.MessageState     `protogen:"open.v1"`
	QueueId            string                     `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	TaskType           string                     `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	RequiredAttributes map[string]*AttributeValue `protobuf:"bytes,3,rep,name=required_attributes,json=requiredAttributes,proto3" json:"required_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optional caller-supplied task ID; server-generated if empty.
	TaskId string `protobuf:"bytes,4,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	// Optional caller-supplied enqueue timestamp (used internally when a
	// task is returned to Pending, and available to callers for the same
	// "preserve FIFO position" reason); server clock used if unset.
	EnqueuedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=enqueued_at,json=enqueuedAt,proto3" json:"enqueued_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueTaskRequest) Reset() {
	*x = EnqueueTaskRequest{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueTaskRequest) ProtoMessage() {}

func (x *EnqueueTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueTaskRequest.ProtoReflect.Descriptor instead.
func (*EnqueueTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{18}
}

func (x *EnqueueTaskRequest) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

func (x *EnqueueTaskRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *EnqueueTaskRequest) GetRequiredAttributes() map[string]*AttributeValue {
	if x != nil {
		return x.RequiredAttributes
	}
	return nil
}

func (x *EnqueueTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *EnqueueTaskRequest) GetEnqueuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnqueuedAt
	}
	return nil
}

type ListTasksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksRequest) Reset() {
	*x = ListTasksRequest{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksRequest) ProtoMessage() {}

func (x *ListTasksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksRequest.ProtoReflect.Descriptor instead.
func (*ListTasksRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{19}
}

type ListTasksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksResponse) Reset() {
	*x = ListTasksResponse{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksResponse) ProtoMessage() {}

func (x *ListTasksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksResponse.ProtoReflect.Descriptor instead.
func (*ListTasksResponse) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{20}
}

func (x *ListTasksResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{21}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type CompleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskRequest) Reset() {
	*x = CompleteTaskRequest{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskRequest) ProtoMessage() {}

func (x *CompleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskRequest.ProtoReflect.Descriptor instead.
func (*CompleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{22}
}

func (x *CompleteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type AcceptReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcceptReservationRequest) Reset() {
	*x = AcceptReservationRequest{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceptReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptReservationRequest) ProtoMessage() {}

func (x *AcceptReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptReservationRequest.ProtoReflect.Descriptor instead.
func (*AcceptReservationRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{23}
}

func (x *AcceptReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type RejectReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RejectReservationRequest) Reset() {
	*x = RejectReservationRequest{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RejectReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectReservationRequest) ProtoMessage() {}

func (x *RejectReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectReservationRequest.ProtoReflect.Descriptor instead.
func (*RejectReservationRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{24}
}

func (x *RejectReservationRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type GetDashboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardRequest) Reset() {
	*x = GetDashboardRequest{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardRequest) ProtoMessage() {}

func (x *GetDashboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardRequest.ProtoReflect.Descriptor instead.
func (*GetDashboardRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{25}
}

type GetDashboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*DashboardAgent      `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	Tasks         []*Task                `protobuf:"bytes,2,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDashboardResponse) Reset() {
	*x = GetDashboardResponse{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDashboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDashboardResponse) ProtoMessage() {}

func (x *GetDashboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDashboardResponse.ProtoReflect.Descriptor instead.
func (*GetDashboardResponse) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{26}
}

func (x *GetDashboardResponse) GetAgents() []*DashboardAgent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *GetDashboardResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type DashboardAgent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Agent *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	// Live count of tasks currently assigned to this agent (Reserved +
	// Active tasks where assigned_agent_id == this agent), for the
	// monitoring display (spec Section 3.7).
	AssignedTaskCount int32 `protobuf:"varint,2,opt,name=assigned_task_count,json=assignedTaskCount,proto3" json:"assigned_task_count,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DashboardAgent) Reset() {
	*x = DashboardAgent{}
	mi := &file_task_router_v1_task_router_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DashboardAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DashboardAgent) ProtoMessage() {}

func (x *DashboardAgent) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DashboardAgent.ProtoReflect.Descriptor instead.
func (*DashboardAgent) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_proto_rawDescGZIP(), []int{27}
}

func (x *DashboardAgent) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *DashboardAgent) GetAssignedTaskCount() int32 {
	if x != nil {
		return x.AssignedTaskCount
	}
	return 0
}

var File_task_router_v1_task_router_proto protoreflect.FileDescriptor

const file_task_router_v1_task_router_proto_rawDesc = "" +
	"\n" +
	" task-router/v1/task_router.proto\x12\rtaskrouter.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"^\n" +
	"\x0eAttributeValue\x12#\n" +
	"\fnumber_value\x18\x01 \x01(\x01H\x00R\vnumberValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x02 \x01(\bH\x00R\tboolValueB\x06\n" +
	"\x04kind\"w\n" +
	"\x0fChannelCapacity\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x05R\x03max\x12\x16\n" +
	"\x06active\x18\x03 \x01(\x05R\x06active\x12$\n" +
	"\rinterruptible\x18\x04 \x01(\bR\rinterruptible\"\xf4\x03\n" +
	"\x05Agent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12D\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2$.taskrouter.v1.Agent.AttributesEntryR\n" +
	"attributes\x12>\n" +
	"\bcapacity\x18\x04 \x03(\v2\".taskrouter.v1.Agent.CapacityEntryR\bcapacity\x12\x16\n" +
	"\x06queues\x18\x05 \x03(\tR\x06queues\x12F\n" +
	"\x11status_changed_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0fstatusChangedAt\x12\x17\n" +
	"\auser_id\x18\a \x01(\tR\x06userId\x1a\\\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.taskrouter.v1.AttributeValueR\x05value:\x028\x01\x1a[\n" +
	"\rCapacityEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.taskrouter.v1.ChannelCapacityR\x05value:\x028\x01\"\xd2\x03\n" +
	"\x04Task\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x19\n" +
	"\bqueue_id\x18\x02 \x01(\tR\aqueueId\x12\x1b\n" +
	"\ttask_type\x18\x03 \x01(\tR\btaskType\x12\\\n" +
	"\x13required_attributes\x18\x04 \x03(\v2+.taskrouter.v1.Task.RequiredAttributesEntryR\x12requiredAttributes\x12;\n" +
	"\venqueued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enqueuedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x124\n" +
	"\x16current_reservation_id\x18\a \x01(\tR\x14currentReservationId\x12*\n" +
	"\x11assigned_agent_id\x18\b \x01(\tR\x0fassignedAgentId\x1ad\n" +
	"\x17RequiredAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.taskrouter.v1.AttributeValueR\x05value:\x028\x01\"\xf6\x01\n" +
	"\vReservation\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\x12\x17\n" +
	"\atask_id\x18\x02 \x01(\tR\x06taskId\x12\x19\n" +
	"\bagent_id\x18\x03 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\xd3\x03\n" +
	"\x12CreateAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12Q\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v21.taskrouter.v1.CreateAgentRequest.AttributesEntryR\n" +
	"attributes\x12K\n" +
	"\bcapacity\x18\x04 \x03(\v2/.taskrouter.v1.CreateAgentRequest.CapacityEntryR\bcapacity\x12\x16\n" +
	"\x06queues\x18\x05 \x03(\tR\x06queues\x12\x17\n" +
	"\auser_id\x18\x06 \x01(\tR\x06userId\x1a\\\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.taskrouter.v1.AttributeValueR\x05value:\x028\x01\x1a[\n" +
	"\rCapacityEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.taskrouter.v1.ChannelCapacityR\x05value:\x028\x01\"\x13\n" +
	"\x11ListAgentsRequest\"B\n" +
	"\x12ListAgentsResponse\x12,\n" +
	"\x06agents\x18\x01 \x03(\v2\x14.taskrouter.v1.AgentR\x06agents\",\n" +
	"\x0fGetAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"/\n" +
	"\x12DeleteAgentRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"Z\n" +
	"\x13DeleteAgentResponse\x12C\n" +
	"\x1eresolved_in_flight_reservation\x18\x01 \x01(\bR\x1bresolvedInFlightReservation\"J\n" +
	"\x15SetAgentStatusRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xeb\x01\n" +
	"\x1bReplaceAgentCapacityRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12T\n" +
	"\bcapacity\x18\x02 \x03(\v28.taskrouter.v1.ReplaceAgentCapacityRequest.CapacityEntryR\bcapacity\x1a[\n" +
	"\rCapacityEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.taskrouter.v1.ChannelCapacityR\x05value:\x028\x01\"f\n" +
	"\x19ToggleChannelReadyRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x14\n" +
	"\x05ready\x18\x03 \x01(\bR\x05ready\"N\n" +
	"\x19ReplaceAgentQueuesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x16\n" +
	"\x06queues\x18\x02 \x03(\tR\x06queues\"\xf6\x01\n" +
	"\x1dReplaceAgentAttributesRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\\\n" +
	"\n" +
	"attributes\x18\x02 \x03(\v2<.taskrouter.v1.ReplaceAgentAttributesRequest.AttributesEntryR\n" +
	"attributes\x1a\\\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.taskrouter.v1.AttributeValueR\x05value:\x028\x01\":\n" +
	"\x1dListAgentPendingOffersRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"`\n" +
	"\x1eListAgentPendingOffersResponse\x12>\n" +
	"\freservations\x18\x01 \x03(\v2\x1a.taskrouter.v1.ReservationR\freservations\"\xf4\x02\n" +
	"\x12EnqueueTaskRequest\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\tR\aqueueId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12j\n" +
	"\x13required_attributes\x18\x03 \x03(\v29.taskrouter.v1.EnqueueTaskRequest.RequiredAttributesEntryR\x12requiredAttributes\x12\x17\n" +
	"\atask_id\x18\x04 \x01(\tR\x06taskId\x12;\n" +
	"\venqueued_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enqueuedAt\x1ad\n" +
	"\x17RequiredAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x123\n" +
	"\x05value\x18\x02 \x01(\v2\x1d.taskrouter.v1.AttributeValueR\x05value:\x028\x01\"\x12\n" +
	"\x10ListTasksRequest\">\n" +
	"\x11ListTasksResponse\x12)\n" +
	"\x05tasks\x18\x01 \x03(\v2\x13.taskrouter.v1.TaskR\x05tasks\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\".\n" +
	"\x13CompleteTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"A\n" +
	"\x18AcceptReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"A\n" +
	"\x18RejectReservationRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"\x15\n" +
	"\x13GetDashboardRequest\"x\n" +
	"\x14GetDashboardResponse\x125\n" +
	"\x06agents\x18\x01 \x03(\v2\x1d.taskrouter.v1.DashboardAgentR\x06agents\x12)\n" +
	"\x05tasks\x18\x02 \x03(\v2\x13.taskrouter.v1.TaskR\x05tasks\"l\n" +
	"\x0eDashboardAgent\x12*\n" +
	"\x05agent\x18\x01 \x01(\v2\x14.taskrouter.v1.AgentR\x05agent\x12.\n" +
	"\x13assigned_task_count\x18\x02 \x01(\x05R\x11assignedTaskCount2\x86\x10\n" +
	"\x11TaskRouterService\x12]\n" +
	"\vCreateAgent\x12!.taskrouter.v1.CreateAgentRequest\x1a\x14.taskrouter.v1.Agent\"\x15\x82\xd3\xe4\x93\x02\x0f:\x01*\"\n" +
	"/v1/agents\x12e\n" +
	"\n" +
	"ListAgents\x12 .taskrouter.v1.ListAgentsRequest\x1a!.taskrouter.v1.ListAgentsResponse\"\x12\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/agents\x12_\n" +
	"\bGetAgent\x12\x1e.taskrouter.v1.GetAgentRequest\x1a\x14.taskrouter.v1.Agent\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/agents/{agent_id}\x12s\n" +
	"\vDeleteAgent\x12!.taskrouter.v1.DeleteAgentRequest\x1a\".taskrouter.v1.DeleteAgentResponse\"\x1d\x82\xd3\xe4\x93\x02\x17*\x15/v1/agents/{agent_id}\x12u\n" +
	"\x0eSetAgentStatus\x12$.taskrouter.v1.SetAgentStatusRequest\x1a\x14.taskrouter.v1.Agent\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/agents/{agent_id}/status\x12\x83\x01\n" +
	"\x14ReplaceAgentCapacity\x12*.taskrouter.v1.ReplaceAgentCapacityRequest\x1a\x14.taskrouter.v1.Agent\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/v1/agents/{agent_id}/capacity\x12\x90\x01\n" +
	"\x12ToggleChannelReady\x12(.taskrouter.v1.ToggleChannelReadyRequest\x1a\x14.taskrouter.v1.Agent\":\x82\xd3\xe4\x93\x024:\x01*\"//v1/agents/{agent_id}/capacity/{channel}/toggle\x12}\n" +
	"\x12ReplaceAgentQueues\x12(.taskrouter.v1.ReplaceAgentQueuesRequest\x1a\x14.taskrouter.v1.Agent\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/agents/{agent_id}/queues\x12\x89\x01\n" +
	"\x16ReplaceAgentAttributes\x12,.taskrouter.v1.ReplaceAgentAttributesRequest\x1a\x14.taskrouter.v1.Agent\"+\x82\xd3\xe4\x93\x02%:\x01*\" /v1/agents/{agent_id}/attributes\x12\x9b\x01\n" +
	"\x16ListAgentPendingOffers\x12,.taskrouter.v1.ListAgentPendingOffersRequest\x1a-.taskrouter.v1.ListAgentPendingOffersResponse\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/v1/agents/{agent_id}/offers\x12[\n" +
	"\vEnqueueTask\x12!.taskrouter.v1.EnqueueTaskRequest\x1a\x13.taskrouter.v1.Task\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/tasks\x12a\n" +
	"\tListTasks\x12\x1f.taskrouter.v1.ListTasksRequest\x1a .taskrouter.v1.ListTasksResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/tasks\x12Z\n" +
	"\aGetTask\x12\x1d.taskrouter.v1.GetTaskRequest\x1a\x13.taskrouter.v1.Task\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/tasks/{task_id}\x12p\n" +
	"\fCompleteTask\x12\".taskrouter.v1.CompleteTaskRequest\x1a\x13.taskrouter.v1.Task\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/v1/tasks/{task_id}/complete\x12\x8d\x01\n" +
	"\x11AcceptReservation\x12'.taskrouter.v1.AcceptReservationRequest\x1a\x1a.taskrouter.v1.Reservation\"3\x82\xd3\xe4\x93\x02-:\x01*\"(/v1/reservations/{reservation_id}/accept\x12\x8d\x01\n" +
	"\x11RejectReservation\x12'.taskrouter.v1.RejectReservationRequest\x1a\x1a.taskrouter.v1.Reservation\"3\x82\xd3\xe4\x93\x02-:\x01*\"(/v1/reservations/{reservation_id}/reject\x12n\n" +
	"\fGetDashboard\x12\".taskrouter.v1.GetDashboardRequest\x1a#.taskrouter.v1.GetDashboardResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/v1/dashboardBRZPgithub.com/thecraftynoob/ProjectPoutine/pkg/genproto/task-router/v1;taskrouterv1b\x06proto3"

var (
	file_task_router_v1_task_router_proto_rawDescOnce sync.Once
	file_task_router_v1_task_router_proto_rawDescData []byte
)

func file_task_router_v1_task_router_proto_rawDescGZIP() []byte {
	file_task_router_v1_task_router_proto_rawDescOnce.Do(func() {
		file_task_router_v1_task_router_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_router_v1_task_router_proto_rawDesc), len(file_task_router_v1_task_router_proto_rawDesc)))
	})
	return file_task_router_v1_task_router_proto_rawDescData
}

var file_task_router_v1_task_router_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_task_router_v1_task_router_proto_goTypes = []any{
	(*AttributeValue)(nil),                 // 0: taskrouter.v1.AttributeValue
	(*ChannelCapacity)(nil),                // 1: taskrouter.v1.ChannelCapacity
	(*Agent)(nil),                          // 2: taskrouter.v1.Agent
	(*Task)(nil),                           // 3: taskrouter.v1.Task
	(*Reservation)(nil),                    // 4: taskrouter.v1.Reservation
	(*CreateAgentRequest)(nil),             // 5: taskrouter.v1.CreateAgentRequest
	(*ListAgentsRequest)(nil),              // 6: taskrouter.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),             // 7: taskrouter.v1.ListAgentsResponse
	(*GetAgentRequest)(nil),                // 8: taskrouter.v1.GetAgentRequest
	(*DeleteAgentRequest)(nil),             // 9: taskrouter.v1.DeleteAgentRequest
	(*DeleteAgentResponse)(nil),            // 10: taskrouter.v1.DeleteAgentResponse
	(*SetAgentStatusRequest)(nil),          // 11: taskrouter.v1.SetAgentStatusRequest
	(*ReplaceAgentCapacityRequest)(nil),    // 12: taskrouter.v1.ReplaceAgentCapacityRequest
	(*ToggleChannelReadyRequest)(nil),      // 13: taskrouter.v1.ToggleChannelReadyRequest
	(*ReplaceAgentQueuesRequest)(nil),      // 14: taskrouter.v1.ReplaceAgentQueuesRequest
	(*ReplaceAgentAttributesRequest)(nil),  // 15: taskrouter.v1.ReplaceAgentAttributesRequest
	(*ListAgentPendingOffersRequest)(nil),  // 16: taskrouter.v1.ListAgentPendingOffersRequest
	(*ListAgentPendingOffersResponse)(nil), // 17: taskrouter.v1.ListAgentPendingOffersResponse
	(*EnqueueTaskRequest)(nil),             // 18: taskrouter.v1.EnqueueTaskRequest
	(*ListTasksRequest)(nil),               // 19: taskrouter.v1.ListTasksRequest
	(*ListTasksResponse)(nil),              // 20: taskrouter.v1.ListTasksResponse
	(*GetTaskRequest)(nil),                 // 21: taskrouter.v1.GetTaskRequest
	(*CompleteTaskRequest)(nil),            // 22: taskrouter.v1.CompleteTaskRequest
	(*AcceptReservationRequest)(nil),       // 23: taskrouter.v1.AcceptReservationRequest
	(*RejectReservationRequest)(nil),       // 24: taskrouter.v1.RejectReservationRequest
	(*GetDashboardRequest)(nil),            // 25: taskrouter.v1.GetDashboardRequest
	(*GetDashboardResponse)(nil),           // 26: taskrouter.v1.GetDashboardResponse
	(*DashboardAgent)(nil),                 // 27: taskrouter.v1.DashboardAgent
	nil,                                    // 28: taskrouter.v1.Agent.AttributesEntry
	nil,                                    // 29: taskrouter.v1.Agent.CapacityEntry
	nil,                                    // 30: taskrouter.v1.Task.RequiredAttributesEntry
	nil,                                    // 31: taskrouter.v1.CreateAgentRequest.AttributesEntry
	nil,                                    // 32: taskrouter.v1.CreateAgentRequest.CapacityEntry
	nil,                                    // 33: taskrouter.v1.ReplaceAgentCapacityRequest.CapacityEntry
	nil,                                    // 34: taskrouter.v1.ReplaceAgentAttributesRequest.AttributesEntry
	nil,                                    // 35: taskrouter.v1.EnqueueTaskRequest.RequiredAttributesEntry
	(*timestamppb.Timestamp)(nil),          // 36: google.protobuf.Timestamp
}
var file_task_router_v1_task_router_proto_depIdxs = []int32{
	28, // 0: taskrouter.v1.Agent.attributes:type_name -> taskrouter.v1.Agent.AttributesEntry
	29, // 1: taskrouter.v1.Agent.capacity:type_name -> taskrouter.v1.Agent.CapacityEntry
	36, // 2: taskrouter.v1.Agent.status_changed_at:type_name -> google.protobuf.Timestamp
	30, // 3: taskrouter.v1.Task.required_attributes:type_name -> taskrouter.v1.Task.RequiredAttributesEntry
	36, // 4: taskrouter.v1.Task.enqueued_at:type_name -> google.protobuf.Timestamp
	36, // 5: taskrouter.v1.Reservation.created_at:type_name -> google.protobuf.Timestamp
	36, // 6: taskrouter.v1.Reservation.expires_at:type_name -> google.protobuf.Timestamp
	31, // 7: taskrouter.v1.CreateAgentRequest.attributes:type_name -> taskrouter.v1.CreateAgentRequest.AttributesEntry
	32, // 8: taskrouter.v1.CreateAgentRequest.capacity:type_name -> taskrouter.v1.CreateAgentRequest.CapacityEntry
	2,  // 9: taskrouter.v1.ListAgentsResponse.agents:type_name -> taskrouter.v1.Agent
	33, // 10: taskrouter.v1.ReplaceAgentCapacityRequest.capacity:type_name -> taskrouter.v1.ReplaceAgentCapacityRequest.CapacityEntry
	34, // 11: taskrouter.v1.ReplaceAgentAttributesRequest.attributes:type_name -> taskrouter.v1.ReplaceAgentAttributesRequest.AttributesEntry
	4,  // 12: taskrouter.v1.ListAgentPendingOffersResponse.reservations:type_name -> taskrouter.v1.Reservation
	35, // 13: taskrouter.v1.EnqueueTaskRequest.required_attributes:type_name -> taskrouter.v1.EnqueueTaskRequest.RequiredAttributesEntry
	36, // 14: taskrouter.v1.EnqueueTaskRequest.enqueued_at:type_name -> google.protobuf.Timestamp
	3,  // 15: taskrouter.v1.ListTasksResponse.tasks:type_name -> taskrouter.v1.Task
	27, // 16: taskrouter.v1.GetDashboardResponse.agents:type_name -> taskrouter.v1.DashboardAgent
	3,  // 17: taskrouter.v1.GetDashboardResponse.tasks:type_name -> taskrouter.v1.Task
	2,  // 18: taskrouter.v1.DashboardAgent.agent:type_name -> taskrouter.v1.Agent
	0,  // 19: taskrouter.v1.Agent.AttributesEntry.value:type_name -> taskrouter.v1.AttributeValue
	1,  // 20: taskrouter.v1.Agent.CapacityEntry.value:type_name -> taskrouter.v1.ChannelCapacity
	0,  // 21: taskrouter.v1.Task.RequiredAttributesEntry.value:type_name -> taskrouter.v1.AttributeValue
	0,  // 22: taskrouter.v1.CreateAgentRequest.AttributesEntry.value:type_name -> taskrouter.v1.AttributeValue
	1,  // 23: taskrouter.v1.CreateAgentRequest.CapacityEntry.value:type_name -> taskrouter.v1.ChannelCapacity
	1,  // 24: taskrouter.v1.ReplaceAgentCapacityRequest.CapacityEntry.value:type_name -> taskrouter.v1.ChannelCapacity
	0,  // 25: taskrouter.v1.ReplaceAgentAttributesRequest.AttributesEntry.value:type_name -> taskrouter.v1.AttributeValue
	0,  // 26: taskrouter.v1.EnqueueTaskRequest.RequiredAttributesEntry.value:type_name -> taskrouter.v1.AttributeValue
	5,  // 27: taskrouter.v1.TaskRouterService.CreateAgent:input_type -> taskrouter.v1.CreateAgentRequest
	6,  // 28: taskrouter.v1.TaskRouterService.ListAgents:input_type -> taskrouter.v1.ListAgentsRequest
	8,  // 29: taskrouter.v1.TaskRouterService.GetAgent:input_type -> taskrouter.v1.GetAgentRequest
	9,  // 30: taskrouter.v1.TaskRouterService.DeleteAgent:input_type -> taskrouter.v1.DeleteAgentRequest
	11, // 31: taskrouter.v1.TaskRouterService.SetAgentStatus:input_type -> taskrouter.v1.SetAgentStatusRequest
	12, // 32: taskrouter.v1.TaskRouterService.ReplaceAgentCapacity:input_type -> taskrouter.v1.ReplaceAgentCapacityRequest
	13, // 33: taskrouter.v1.TaskRouterService.ToggleChannelReady:input_type -> taskrouter.v1.ToggleChannelReadyRequest
	14, // 34: taskrouter.v1.TaskRouterService.ReplaceAgentQueues:input_type -> taskrouter.v1.ReplaceAgentQueuesRequest
	15, // 35: taskrouter.v1.TaskRouterService.ReplaceAgentAttributes:input_type -> taskrouter.v1.ReplaceAgentAttributesRequest
	16, // 36: taskrouter.v1.TaskRouterService.ListAgentPendingOffers:input_type -> taskrouter.v1.ListAgentPendingOffersRequest
	18, // 37: taskrouter.v1.TaskRouterService.EnqueueTask:input_type -> taskrouter.v1.EnqueueTaskRequest
	19, // 38: taskrouter.v1.TaskRouterService.ListTasks:input_type -> taskrouter.v1.ListTasksRequest
	21, // 39: taskrouter.v1.TaskRouterService.GetTask:input_type -> taskrouter.v1.GetTaskRequest
	22, // 40: taskrouter.v1.TaskRouterService.CompleteTask:input_type -> taskrouter.v1.CompleteTaskRequest
	23, // 41: taskrouter.v1.TaskRouterService.AcceptReservation:input_type -> taskrouter.v1.AcceptReservationRequest
	24, // 42: taskrouter.v1.TaskRouterService.RejectReservation:input_type -> taskrouter.v1.RejectReservationRequest
	25, // 43: taskrouter.v1.TaskRouterService.GetDashboard:input_type -> taskrouter.v1.GetDashboardRequest
	2,  // 44: taskrouter.v1.TaskRouterService.CreateAgent:output_type -> taskrouter.v1.Agent
	7,  // 45: taskrouter.v1.TaskRouterService.ListAgents:output_type -> taskrouter.v1.ListAgentsResponse
	2,  // 46: taskrouter.v1.TaskRouterService.GetAgent:output_type -> taskrouter.v1.Agent
	10, // 47: taskrouter.v1.TaskRouterService.DeleteAgent:output_type -> taskrouter.v1.DeleteAgentResponse
	2,  // 48: taskrouter.v1.TaskRouterService.SetAgentStatus:output_type -> taskrouter.v1.Agent
	2,  // 49: taskrouter.v1.TaskRouterService.ReplaceAgentCapacity:output_type -> taskrouter.v1.Agent
	2,  // 50: taskrouter.v1.TaskRouterService.ToggleChannelReady:output_type -> taskrouter.v1.Agent
	2,  // 51: taskrouter.v1.TaskRouterService.ReplaceAgentQueues:output_type -> taskrouter.v1.Agent
	2,  // 52: taskrouter.v1.TaskRouterService.ReplaceAgentAttributes:output_type -> taskrouter.v1.Agent
	17, // 53: taskrouter.v1.TaskRouterService.ListAgentPendingOffers:output_type -> taskrouter.v1.ListAgentPendingOffersResponse
	3,  // 54: taskrouter.v1.TaskRouterService.EnqueueTask:output_type -> taskrouter.v1.Task
	20, // 55: taskrouter.v1.TaskRouterService.ListTasks:output_type -> taskrouter.v1.ListTasksResponse
	3,  // 56: taskrouter.v1.TaskRouterService.GetTask:output_type -> taskrouter.v1.Task
	3,  // 57: taskrouter.v1.TaskRouterService.CompleteTask:output_type -> taskrouter.v1.Task
	4,  // 58: taskrouter.v1.TaskRouterService.AcceptReservation:output_type -> taskrouter.v1.Reservation
	4,  // 59: taskrouter.v1.TaskRouterService.RejectReservation:output_type -> taskrouter.v1.Reservation
	26, // 60: taskrouter.v1.TaskRouterService.GetDashboard:output_type -> taskrouter.v1.GetDashboardResponse
	44, // [44:61] is the sub-list for method output_type
	27, // [27:44] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_task_router_v1_task_router_proto_init() }
func file_task_router_v1_task_router_proto_init() {
	if File_task_router_v1_task_router_proto != nil {
		return
	}
	file_task_router_v1_task_router_proto_msgTypes[0].OneofWrappers = []any{
		(*AttributeValue_NumberValue)(nil),
		(*AttributeValue_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_router_v1_task_router_proto_rawDesc), len(file_task_router_v1_task_router_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_router_v1_task_router_proto_goTypes,
		DependencyIndexes: file_task_router_v1_task_router_proto_depIdxs,
		MessageInfos:      file_task_router_v1_task_router_proto_msgTypes,
	}.Build()
	File_task_router_v1_task_router_proto = out.File
	file_task_router_v1_task_router_proto_goTypes = nil
	file_task_router_v1_task_router_proto_depIdxs = nil
}
