// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: task-router/v1/task_router_admin.proto

package taskrouterv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskRouterAdminService_RegisterQueue_FullMethodName     = "/taskrouter.v1.TaskRouterAdminService/RegisterQueue"
	TaskRouterAdminService_ListQueues_FullMethodName        = "/taskrouter.v1.TaskRouterAdminService/ListQueues"
	TaskRouterAdminService_GetQueue_FullMethodName          = "/taskrouter.v1.TaskRouterAdminService/GetQueue"
	TaskRouterAdminService_RemoveQueue_FullMethodName       = "/taskrouter.v1.TaskRouterAdminService/RemoveQueue"
	TaskRouterAdminService_RegisterStatus_FullMethodName    = "/taskrouter.v1.TaskRouterAdminService/RegisterStatus"
	TaskRouterAdminService_ListStatuses_FullMethodName      = "/taskrouter.v1.TaskRouterAdminService/ListStatuses"
	TaskRouterAdminService_RemoveStatus_FullMethodName      = "/taskrouter.v1.TaskRouterAdminService/RemoveStatus"
	TaskRouterAdminService_RegisterAttribute_FullMethodName = "/taskrouter.v1.TaskRouterAdminService/RegisterAttribute"
	TaskRouterAdminService_ListAttributes_FullMethodName    = "/taskrouter.v1.TaskRouterAdminService/ListAttributes"
	TaskRouterAdminService_GetAttribute_FullMethodName      = "/taskrouter.v1.TaskRouterAdminService/GetAttribute"
	TaskRouterAdminService_RemoveAttribute_FullMethodName   = "/taskrouter.v1.TaskRouterAdminService/RemoveAttribute"
)

// TaskRouterAdminServiceClient is the client API for TaskRouterAdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TaskRouterAdminService is the low-change configuration domain contract
// for the Task Router (TASK_ROUTER_SPECIFICATION.md Sections 3.1, 3.6):
// Queue registry, Status registry, and Attribute registry. Backed by
// Postgres (via pkg/pgtenant) rather than the Redis hot path, since this
// data is long-lived, transactionally queried, and rarely mutated
// (architecture doc Section 3.1, Tier 2).
//
// NOTE: tenant_id is deliberately NOT a field on any message here — see
// TaskRouterService's note on tenant scoping via gRPC metadata.
type TaskRouterAdminServiceClient interface {
	// RegisterQueue creates a new named work bucket. Rejected if the ID
	// already exists.
	RegisterQueue(ctx context.Context, in *RegisterQueueRequest, opts ...grpc.CallOption) (*Queue, error)
	// ListQueues enumerates all registered queues.
	ListQueues(ctx context.Context, in *ListQueuesRequest, opts ...grpc.CallOption) (*ListQueuesResponse, error)
	// GetQueue retrieves one queue plus every agent currently a member of
	// it.
	GetQueue(ctx context.Context, in *GetQueueRequest, opts ...grpc.CallOption) (*GetQueueResponse, error)
	// RemoveQueue deletes a queue definition. Any agent still listing this
	// queue, or any task still referencing it, is not updated — the
	// reference becomes orphaned rather than blocking the delete.
	RemoveQueue(ctx context.Context, in *RemoveQueueRequest, opts ...grpc.CallOption) (*RemoveQueueResponse, error)
	// RegisterStatus extends the allow-list of valid agent statuses.
	// Rejected if already present.
	RegisterStatus(ctx context.Context, in *RegisterStatusRequest, opts ...grpc.CallOption) (*StatusEntry, error)
	// ListStatuses enumerates the registry.
	ListStatuses(ctx context.Context, in *ListStatusesRequest, opts ...grpc.CallOption) (*ListStatusesResponse, error)
	// RemoveStatus shrinks the allow-list. Agents currently set to this
	// status are unaffected; the removal only blocks future assignment.
	RemoveStatus(ctx context.Context, in *RemoveStatusRequest, opts ...grpc.CallOption) (*RemoveStatusResponse, error)
	// RegisterAttribute defines a new named, typed field usable in Agent/
	// Task attribute maps. Rejected on invalid type or duplicate name.
	RegisterAttribute(ctx context.Context, in *RegisterAttributeRequest, opts ...grpc.CallOption) (*AttributeDefinition, error)
	// ListAttributes enumerates the registry.
	ListAttributes(ctx context.Context, in *ListAttributesRequest, opts ...grpc.CallOption) (*ListAttributesResponse, error)
	// GetAttribute retrieves one attribute's definition plus every agent
	// currently assigned a value for it.
	GetAttribute(ctx context.Context, in *GetAttributeRequest, opts ...grpc.CallOption) (*GetAttributeResponse, error)
	// RemoveAttribute retires a named field. Existing agent/task values
	// referencing it are unaffected; removal only blocks future use.
	RemoveAttribute(ctx context.Context, in *RemoveAttributeRequest, opts ...grpc.CallOption) (*RemoveAttributeResponse, error)
}

type taskRouterAdminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskRouterAdminServiceClient(cc grpc.ClientConnInterface) TaskRouterAdminServiceClient {
	return &taskRouterAdminServiceClient{cc}
}

func (c *taskRouterAdminServiceClient) RegisterQueue(ctx context.Context, in *RegisterQueueRequest, opts ...grpc.CallOption) (*Queue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Queue)
	err := c.cc.Invoke(ctx, TaskRouterAdminService_RegisterQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterAdminServiceClient) ListQueues(ctx context.Context, in *ListQueuesRequest, opts ...grpc.CallOption) (*ListQueuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListQueuesResponse)
	err := c.cc.Invoke(ctx, TaskRouterAdminService_ListQueues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterAdminServiceClient) GetQueue(ctx context.Context, in *GetQueueRequest, opts ...grpc.CallOption) (*GetQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetQueueResponse)
	err := c.cc.Invoke(ctx, TaskRouterAdminService_GetQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterAdminServiceClient) RemoveQueue(ctx context.Context, in *RemoveQueueRequest, opts ...grpc.CallOption) (*RemoveQueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveQueueResponse)
	err := c.cc.Invoke(ctx, TaskRouterAdminService_RemoveQueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterAdminServiceClient) RegisterStatus(ctx context.Context, in *RegisterStatusRequest, opts ...grpc.CallOption) (*StatusEntry, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusEntry)
	err := c.cc.Invoke(ctx, TaskRouterAdminService_RegisterStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterAdminServiceClient) ListStatuses(ctx context.Context, in *ListStatusesRequest, opts ...grpc.CallOption) (*ListStatusesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListStatusesResponse)
	err := c.cc.Invoke(ctx, TaskRouterAdminService_ListStatuses_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterAdminServiceClient) RemoveStatus(ctx context.Context, in *RemoveStatusRequest, opts ...grpc.CallOption) (*RemoveStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveStatusResponse)
	err := c.cc.Invoke(ctx, TaskRouterAdminService_RemoveStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterAdminServiceClient) RegisterAttribute(ctx context.Context, in *RegisterAttributeRequest, opts ...grpc.CallOption) (*AttributeDefinition, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttributeDefinition)
	err := c.cc.Invoke(ctx, TaskRouterAdminService_RegisterAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterAdminServiceClient) ListAttributes(ctx context.Context, in *ListAttributesRequest, opts ...grpc.CallOption) (*ListAttributesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAttributesResponse)
	err := c.cc.Invoke(ctx, TaskRouterAdminService_ListAttributes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterAdminServiceClient) GetAttribute(ctx context.Context, in *GetAttributeRequest, opts ...grpc.CallOption) (*GetAttributeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAttributeResponse)
	err := c.cc.Invoke(ctx, TaskRouterAdminService_GetAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterAdminServiceClient) RemoveAttribute(ctx context.Context, in *RemoveAttributeRequest, opts ...grpc.CallOption) (*RemoveAttributeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveAttributeResponse)
	err := c.cc.Invoke(ctx, TaskRouterAdminService_RemoveAttribute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskRouterAdminServiceServer is the server API for TaskRouterAdminService service.
// All implementations must embed UnimplementedTaskRouterAdminServiceServer
// for forward compatibility.
//
// TaskRouterAdminService is the low-change configuration domain contract
// for the Task Router (TASK_ROUTER_SPECIFICATION.md Sections 3.1, 3.6):
// Queue registry, Status registry, and Attribute registry. Backed by
// Postgres (via pkg/pgtenant) rather than the Redis hot path, since this
// data is long-lived, transactionally queried, and rarely mutated
// (architecture doc Section 3.1, Tier 2).
//
// NOTE: tenant_id is deliberately NOT a field on any message here — see
// TaskRouterService's note on tenant scoping via gRPC metadata.
type TaskRouterAdminServiceServer interface {
	// RegisterQueue creates a new named work bucket. Rejected if the ID
	// already exists.
	RegisterQueue(context.Context, *RegisterQueueRequest) (*Queue, error)
	// ListQueues enumerates all registered queues.
	ListQueues(context.Context, *ListQueuesRequest) (*ListQueuesResponse, error)
	// GetQueue retrieves one queue plus every agent currently a member of
	// it.
	GetQueue(context.Context, *GetQueueRequest) (*GetQueueResponse, error)
	// RemoveQueue deletes a queue definition. Any agent still listing this
	// queue, or any task still referencing it, is not updated — the
	// reference becomes orphaned rather than blocking the delete.
	RemoveQueue(context.Context, *RemoveQueueRequest) (*RemoveQueueResponse, error)
	// RegisterStatus extends the allow-list of valid agent statuses.
	// Rejected if already present.
	RegisterStatus(context.Context, *RegisterStatusRequest) (*StatusEntry, error)
	// ListStatuses enumerates the registry.
	ListStatuses(context.Context, *ListStatusesRequest) (*ListStatusesResponse, error)
	// RemoveStatus shrinks the allow-list. Agents currently set to this
	// status are unaffected; the removal only blocks future assignment.
	RemoveStatus(context.Context, *RemoveStatusRequest) (*RemoveStatusResponse, error)
	// RegisterAttribute defines a new named, typed field usable in Agent/
	// Task attribute maps. Rejected on invalid type or duplicate name.
	RegisterAttribute(context.Context, *RegisterAttributeRequest) (*AttributeDefinition, error)
	// ListAttributes enumerates the registry.
	ListAttributes(context.Context, *ListAttributesRequest) (*ListAttributesResponse, error)
	// GetAttribute retrieves one attribute's definition plus every agent
	// currently assigned a value for it.
	GetAttribute(context.Context, *GetAttributeRequest) (*GetAttributeResponse, error)
	// RemoveAttribute retires a named field. Existing agent/task values
	// referencing it are unaffected; removal only blocks future use.
	RemoveAttribute(context.Context, *RemoveAttributeRequest) (*RemoveAttributeResponse, error)
	mustEmbedUnimplementedTaskRouterAdminServiceServer()
}

// UnimplementedTaskRouterAdminServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskRouterAdminServiceServer struct{}

func (UnimplementedTaskRouterAdminServiceServer) RegisterQueue(context.Context, *RegisterQueueRequest) (*Queue, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterQueue not implemented")
}
func (UnimplementedTaskRouterAdminServiceServer) ListQueues(context.Context, *ListQueuesRequest) (*ListQueuesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListQueues not implemented")
}
func (UnimplementedTaskRouterAdminServiceServer) GetQueue(context.Context, *GetQueueRequest) (*GetQueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetQueue not implemented")
}
func (UnimplementedTaskRouterAdminServiceServer) RemoveQueue(context.Context, *RemoveQueueRequest) (*RemoveQueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveQueue not implemented")
}
func (UnimplementedTaskRouterAdminServiceServer) RegisterStatus(context.Context, *RegisterStatusRequest) (*StatusEntry, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterStatus not implemented")
}
func (UnimplementedTaskRouterAdminServiceServer) ListStatuses(context.Context, *ListStatusesRequest) (*ListStatusesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListStatuses not implemented")
}
func (UnimplementedTaskRouterAdminServiceServer) RemoveStatus(context.Context, *RemoveStatusRequest) (*RemoveStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveStatus not implemented")
}
func (UnimplementedTaskRouterAdminServiceServer) RegisterAttribute(context.Context, *RegisterAttributeRequest) (*AttributeDefinition, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAttribute not implemented")
}
func (UnimplementedTaskRouterAdminServiceServer) ListAttributes(context.Context, *ListAttributesRequest) (*ListAttributesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAttributes not implemented")
}
func (UnimplementedTaskRouterAdminServiceServer) GetAttribute(context.Context, *GetAttributeRequest) (*GetAttributeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAttribute not implemented")
}
func (UnimplementedTaskRouterAdminServiceServer) RemoveAttribute(context.Context, *RemoveAttributeRequest) (*RemoveAttributeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveAttribute not implemented")
}
func (UnimplementedTaskRouterAdminServiceServer) mustEmbedUnimplementedTaskRouterAdminServiceServer() {
}
func (UnimplementedTaskRouterAdminServiceServer) testEmbeddedByValue() {}

// UnsafeTaskRouterAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskRouterAdminServiceServer will
// result in compilation errors.
type UnsafeTaskRouterAdminServiceServer interface {
	mustEmbedUnimplementedTaskRouterAdminServiceServer()
}

func RegisterTaskRouterAdminServiceServer(s grpc.ServiceRegistrar, srv TaskRouterAdminServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskRouterAdminServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskRouterAdminService_ServiceDesc, srv)
}

func _TaskRouterAdminService_RegisterQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterAdminServiceServer).RegisterQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterAdminService_RegisterQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterAdminServiceServer).RegisterQueue(ctx, req.(*RegisterQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterAdminService_ListQueues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListQueuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterAdminServiceServer).ListQueues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterAdminService_ListQueues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterAdminServiceServer).ListQueues(ctx, req.(*ListQueuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterAdminService_GetQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterAdminServiceServer).GetQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterAdminService_GetQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterAdminServiceServer).GetQueue(ctx, req.(*GetQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterAdminService_RemoveQueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveQueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterAdminServiceServer).RemoveQueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterAdminService_RemoveQueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterAdminServiceServer).RemoveQueue(ctx, req.(*RemoveQueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterAdminService_RegisterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterAdminServiceServer).RegisterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterAdminService_RegisterStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterAdminServiceServer).RegisterStatus(ctx, req.(*RegisterStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterAdminService_ListStatuses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStatusesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterAdminServiceServer).ListStatuses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterAdminService_ListStatuses_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterAdminServiceServer).ListStatuses(ctx, req.(*ListStatusesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterAdminService_RemoveStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterAdminServiceServer).RemoveStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterAdminService_RemoveStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterAdminServiceServer).RemoveStatus(ctx, req.(*RemoveStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterAdminService_RegisterAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterAdminServiceServer).RegisterAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterAdminService_RegisterAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterAdminServiceServer).RegisterAttribute(ctx, req.(*RegisterAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterAdminService_ListAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterAdminServiceServer).ListAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterAdminService_ListAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterAdminServiceServer).ListAttributes(ctx, req.(*ListAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterAdminService_GetAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterAdminServiceServer).GetAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterAdminService_GetAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterAdminServiceServer).GetAttribute(ctx, req.(*GetAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterAdminService_RemoveAttribute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveAttributeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterAdminServiceServer).RemoveAttribute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterAdminService_RemoveAttribute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterAdminServiceServer).RemoveAttribute(ctx, req.(*RemoveAttributeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskRouterAdminService_ServiceDesc is the grpc.ServiceDesc for TaskRouterAdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskRouterAdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taskrouter.v1.TaskRouterAdminService",
	HandlerType: (*TaskRouterAdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterQueue",
			Handler:    _TaskRouterAdminService_RegisterQueue_Handler,
		},
		{
			MethodName: "ListQueues",
			Handler:    _TaskRouterAdminService_ListQueues_Handler,
		},
		{
			MethodName: "GetQueue",
			Handler:    _TaskRouterAdminService_GetQueue_Handler,
		},
		{
			MethodName: "RemoveQueue",
			Handler:    _TaskRouterAdminService_RemoveQueue_Handler,
		},
		{
			MethodName: "RegisterStatus",
			Handler:    _TaskRouterAdminService_RegisterStatus_Handler,
		},
		{
			MethodName: "ListStatuses",
			Handler:    _TaskRouterAdminService_ListStatuses_Handler,
		},
		{
			MethodName: "RemoveStatus",
			Handler:    _TaskRouterAdminService_RemoveStatus_Handler,
		},
		{
			MethodName: "RegisterAttribute",
			Handler:    _TaskRouterAdminService_RegisterAttribute_Handler,
		},
		{
			MethodName: "ListAttributes",
			Handler:    _TaskRouterAdminService_ListAttributes_Handler,
		},
		{
			MethodName: "GetAttribute",
			Handler:    _TaskRouterAdminService_GetAttribute_Handler,
		},
		{
			MethodName: "RemoveAttribute",
			Handler:    _TaskRouterAdminService_RemoveAttribute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task-router/v1/task_router_admin.proto",
}
