// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: task-router/v1/task_router_admin.proto

package taskrouterv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AttributeType enumerates the two permitted Attribute registry types
// (spec Section 2.6).
type AttributeType int32

const (
	AttributeType_ATTRIBUTE_TYPE_UNSPECIFIED AttributeType = 0
	AttributeType_ATTRIBUTE_TYPE_NUMERIC     AttributeType = 1
	AttributeType_ATTRIBUTE_TYPE_BOOLEAN     AttributeType = 2
)

// Enum value maps for AttributeType.
var (
	AttributeType_name = map[int32]string{
		0: "ATTRIBUTE_TYPE_UNSPECIFIED",
		1: "ATTRIBUTE_TYPE_NUMERIC",
		2: "ATTRIBUTE_TYPE_BOOLEAN",
	}
	AttributeType_value = map[string]int32{
		"ATTRIBUTE_TYPE_UNSPECIFIED": 0,
		"ATTRIBUTE_TYPE_NUMERIC":     1,
		"ATTRIBUTE_TYPE_BOOLEAN":     2,
	}
)

func (x AttributeType) Enum() *AttributeType {
	p := new(AttributeType)
	*p = x
	return p
}

func (x AttributeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttributeType) Descriptor() protoreflect.EnumDescriptor {
	return file_task_router_v1_task_router_admin_proto_enumTypes[0].Descriptor()
}

func (AttributeType) Type() protoreflect.EnumType {
	return &file_task_router_v1_task_router_admin_proto_enumTypes[0]
}

func (x AttributeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttributeType.Descriptor instead.
func (AttributeType) EnumDescriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{0}
}

// Queue mirrors spec Section 2.4 exactly.
type Queue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       string                 `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Queue) Reset() {
	*x = Queue{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Queue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Queue) ProtoMessage() {}

func (x *Queue) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Queue.ProtoReflect.Descriptor instead.
func (*Queue) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{0}
}

func (x *Queue) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

func (x *Queue) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// StatusEntry mirrors spec Section 2.5 exactly.
type StatusEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusEntry) Reset() {
	*x = StatusEntry{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusEntry) ProtoMessage() {}

func (x *StatusEntry) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusEntry.ProtoReflect.Descriptor instead.
func (*StatusEntry) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{1}
}

func (x *StatusEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StatusEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// AttributeDefinition mirrors spec Section 2.6 exactly.
type AttributeDefinition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          AttributeType          `protobuf:"varint,2,opt,name=type,proto3,enum=taskrouter.v1.AttributeType" json:"type,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeDefinition) Reset() {
	*x = AttributeDefinition{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeDefinition) ProtoMessage() {}

func (x *AttributeDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeDefinition.ProtoReflect.Descriptor instead.
func (*AttributeDefinition) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{2}
}

func (x *AttributeDefinition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AttributeDefinition) GetType() AttributeType {
	if x != nil {
		return x.Type
	}
	return AttributeType_ATTRIBUTE_TYPE_UNSPECIFIED
}

func (x *AttributeDefinition) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RegisterQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       string                 `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterQueueRequest) Reset() {
	*x = RegisterQueueRequest{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterQueueRequest) ProtoMessage() {}

func (x *RegisterQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterQueueRequest.ProtoReflect.Descriptor instead.
func (*RegisterQueueRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterQueueRequest) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

type ListQueuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueuesRequest) Reset() {
	*x = ListQueuesRequest{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesRequest) ProtoMessage() {}

func (x *ListQueuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesRequest.ProtoReflect.Descriptor instead.
func (*ListQueuesRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{4}
}

type ListQueuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queues        []*Queue               `protobuf:"bytes,1,rep,name=queues,proto3" json:"queues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueuesResponse) Reset() {
	*x = ListQueuesResponse{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesResponse) ProtoMessage() {}

func (x *ListQueuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesResponse.ProtoReflect.Descriptor instead.
func (*ListQueuesResponse) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{5}
}

func (x *ListQueuesResponse) GetQueues() []*Queue {
	if x != nil {
		return x.Queues
	}
	return nil
}

type GetQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       string                 `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueRequest) Reset() {
	*x = GetQueueRequest{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueRequest) ProtoMessage() {}

func (x *GetQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueRequest.ProtoReflect.Descriptor instead.
func (*GetQueueRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{6}
}

func (x *GetQueueRequest) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

type GetQueueResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Queue *Queue                 `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	// Agent IDs currently a member of this queue.
	MemberAgentIds []string `protobuf:"bytes,2,rep,name=member_agent_ids,json=memberAgentIds,proto3" json:"member_agent_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetQueueResponse) Reset() {
	*x = GetQueueResponse{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueResponse) ProtoMessage() {}

func (x *GetQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueResponse.ProtoReflect.Descriptor instead.
func (*GetQueueResponse) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{7}
}

func (x *GetQueueResponse) GetQueue() *Queue {
	if x != nil {
		return x.Queue
	}
	return nil
}

func (x *GetQueueResponse) GetMemberAgentIds() []string {
	if x != nil {
		return x.MemberAgentIds
	}
	return nil
}

type RemoveQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       string                 `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveQueueRequest) Reset() {
	*x = RemoveQueueRequest{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveQueueRequest) ProtoMessage() {}

func (x *RemoveQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveQueueRequest.ProtoReflect.Descriptor instead.
func (*RemoveQueueRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveQueueRequest) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

type RemoveQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveQueueResponse) Reset() {
	*x = RemoveQueueResponse{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveQueueResponse) ProtoMessage() {}

func (x *RemoveQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveQueueResponse.ProtoReflect.Descriptor instead.
func (*RemoveQueueResponse) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{9}
}

type RegisterStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterStatusRequest) Reset() {
	*x = RegisterStatusRequest{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterStatusRequest) ProtoMessage() {}

func (x *RegisterStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterStatusRequest.ProtoReflect.Descriptor instead.
func (*RegisterStatusRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{10}
}

func (x *RegisterStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ListStatusesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStatusesRequest) Reset() {
	*x = ListStatusesRequest{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStatusesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStatusesRequest) ProtoMessage() {}

func (x *ListStatusesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStatusesRequest.ProtoReflect.Descriptor instead.
func (*ListStatusesRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{11}
}

type ListStatusesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Statuses      []*StatusEntry         `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStatusesResponse) Reset() {
	*x = ListStatusesResponse{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStatusesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStatusesResponse) ProtoMessage() {}

func (x *ListStatusesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStatusesResponse.ProtoReflect.Descriptor instead.
func (*ListStatusesResponse) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{12}
}

func (x *ListStatusesResponse) GetStatuses() []*StatusEntry {
	if x != nil {
		return x.Statuses
	}
	return nil
}

type RemoveStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStatusRequest) Reset() {
	*x = RemoveStatusRequest{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStatusRequest) ProtoMessage() {}

func (x *RemoveStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStatusRequest.ProtoReflect.Descriptor instead.
func (*RemoveStatusRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RemoveStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveStatusResponse) Reset() {
	*x = RemoveStatusResponse{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveStatusResponse) ProtoMessage() {}

func (x *RemoveStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveStatusResponse.ProtoReflect.Descriptor instead.
func (*RemoveStatusResponse) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{14}
}

type RegisterAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          AttributeType          `protobuf:"varint,2,opt,name=type,proto3,enum=taskrouter.v1.AttributeType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAttributeRequest) Reset() {
	*x = RegisterAttributeRequest{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAttributeRequest) ProtoMessage() {}

func (x *RegisterAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAttributeRequest.ProtoReflect.Descriptor instead.
func (*RegisterAttributeRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{15}
}

func (x *RegisterAttributeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterAttributeRequest) GetType() AttributeType {
	if x != nil {
		return x.Type
	}
	return AttributeType_ATTRIBUTE_TYPE_UNSPECIFIED
}

type ListAttributesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttributesRequest) Reset() {
	*x = ListAttributesRequest{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttributesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttributesRequest) ProtoMessage() {}

func (x *ListAttributesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttributesRequest.ProtoReflect.Descriptor instead.
func (*ListAttributesRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{16}
}

type ListAttributesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Attributes    []*AttributeDefinition `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAttributesResponse) Reset() {
	*x = ListAttributesResponse{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAttributesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAttributesResponse) ProtoMessage() {}

func (x *ListAttributesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAttributesResponse.ProtoReflect.Descriptor instead.
func (*ListAttributesResponse) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{17}
}

func (x *ListAttributesResponse) GetAttributes() []*AttributeDefinition {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type GetAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAttributeRequest) Reset() {
	*x = GetAttributeRequest{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributeRequest) ProtoMessage() {}

func (x *GetAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributeRequest.ProtoReflect.Descriptor instead.
func (*GetAttributeRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{18}
}

func (x *GetAttributeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetAttributeResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Attribute *AttributeDefinition   `protobuf:"bytes,1,opt,name=attribute,proto3" json:"attribute,omitempty"`
	// Agent IDs currently assigned a value for this attribute.
	AssignedAgentIds []string `protobuf:"bytes,2,rep,name=assigned_agent_ids,json=assignedAgentIds,proto3" json:"assigned_agent_ids,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetAttributeResponse) Reset() {
	*x = GetAttributeResponse{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAttributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAttributeResponse) ProtoMessage() {}

func (x *GetAttributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAttributeResponse.ProtoReflect.Descriptor instead.
func (*GetAttributeResponse) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{19}
}

func (x *GetAttributeResponse) GetAttribute() *AttributeDefinition {
	if x != nil {
		return x.Attribute
	}
	return nil
}

func (x *GetAttributeResponse) GetAssignedAgentIds() []string {
	if x != nil {
		return x.AssignedAgentIds
	}
	return nil
}

type RemoveAttributeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAttributeRequest) Reset() {
	*x = RemoveAttributeRequest{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAttributeRequest) ProtoMessage() {}

func (x *RemoveAttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAttributeRequest.ProtoReflect.Descriptor instead.
func (*RemoveAttributeRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{20}
}

func (x *RemoveAttributeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RemoveAttributeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveAttributeResponse) Reset() {
	*x = RemoveAttributeResponse{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveAttributeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveAttributeResponse) ProtoMessage() {}

func (x *RemoveAttributeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveAttributeResponse.ProtoReflect.Descriptor instead.
func (*RemoveAttributeResponse) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{21}
}

// Disposition is a tenant-defined tag selectable by an agent during a
// task's WrapUp status, for historical reporting (see
// TaskRouterService.SetTaskDisposition).
type Disposition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DispositionId string                 `protobuf:"bytes,1,opt,name=disposition_id,json=dispositionId,proto3" json:"disposition_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disposition) Reset() {
	*x = Disposition{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disposition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disposition) ProtoMessage() {}

func (x *Disposition) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disposition.ProtoReflect.Descriptor instead.
func (*Disposition) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{22}
}

func (x *Disposition) GetDispositionId() string {
	if x != nil {
		return x.DispositionId
	}
	return ""
}

func (x *Disposition) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Disposition) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RegisterDispositionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional; server-generated if empty.
	DispositionId string `protobuf:"bytes,1,opt,name=disposition_id,json=dispositionId,proto3" json:"disposition_id,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDispositionRequest) Reset() {
	*x = RegisterDispositionRequest{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDispositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDispositionRequest) ProtoMessage() {}

func (x *RegisterDispositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDispositionRequest.ProtoReflect.Descriptor instead.
func (*RegisterDispositionRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{23}
}

func (x *RegisterDispositionRequest) GetDispositionId() string {
	if x != nil {
		return x.DispositionId
	}
	return ""
}

func (x *RegisterDispositionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListDispositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDispositionsRequest) Reset() {
	*x = ListDispositionsRequest{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDispositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDispositionsRequest) ProtoMessage() {}

func (x *ListDispositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDispositionsRequest.ProtoReflect.Descriptor instead.
func (*ListDispositionsRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{24}
}

type ListDispositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dispositions  []*Disposition         `protobuf:"bytes,1,rep,name=dispositions,proto3" json:"dispositions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDispositionsResponse) Reset() {
	*x = ListDispositionsResponse{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDispositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDispositionsResponse) ProtoMessage() {}

func (x *ListDispositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDispositionsResponse.ProtoReflect.Descriptor instead.
func (*ListDispositionsResponse) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{25}
}

func (x *ListDispositionsResponse) GetDispositions() []*Disposition {
	if x != nil {
		return x.Dispositions
	}
	return nil
}

type RemoveDispositionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DispositionId string                 `protobuf:"bytes,1,opt,name=disposition_id,json=dispositionId,proto3" json:"disposition_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDispositionRequest) Reset() {
	*x = RemoveDispositionRequest{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDispositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDispositionRequest) ProtoMessage() {}

func (x *RemoveDispositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDispositionRequest.ProtoReflect.Descriptor instead.
func (*RemoveDispositionRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{26}
}

func (x *RemoveDispositionRequest) GetDispositionId() string {
	if x != nil {
		return x.DispositionId
	}
	return ""
}

type RemoveDispositionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveDispositionResponse) Reset() {
	*x = RemoveDispositionResponse{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveDispositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveDispositionResponse) ProtoMessage() {}

func (x *RemoveDispositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveDispositionResponse.ProtoReflect.Descriptor instead.
func (*RemoveDispositionResponse) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{27}
}

type AssociateQueueDispositionsRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	QueueId string                 `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	// Full replacement list of disposition_ids available to this queue.
	// Rejected entirely (no partial application) if any disposition_id
	// doesn't exist -- mirrors ReplaceAgentQueues' full-replace/all-or-
	// nothing convention (TaskRouterService.ReplaceAgentQueues).
	DispositionIds []string `protobuf:"bytes,2,rep,name=disposition_ids,json=dispositionIds,proto3" json:"disposition_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AssociateQueueDispositionsRequest) Reset() {
	*x = AssociateQueueDispositionsRequest{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssociateQueueDispositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssociateQueueDispositionsRequest) ProtoMessage() {}

func (x *AssociateQueueDispositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssociateQueueDispositionsRequest.ProtoReflect.Descriptor instead.
func (*AssociateQueueDispositionsRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{28}
}

func (x *AssociateQueueDispositionsRequest) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

func (x *AssociateQueueDispositionsRequest) GetDispositionIds() []string {
	if x != nil {
		return x.DispositionIds
	}
	return nil
}

type AssociateQueueDispositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssociateQueueDispositionsResponse) Reset() {
	*x = AssociateQueueDispositionsResponse{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssociateQueueDispositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssociateQueueDispositionsResponse) ProtoMessage() {}

func (x *AssociateQueueDispositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssociateQueueDispositionsResponse.ProtoReflect.Descriptor instead.
func (*AssociateQueueDispositionsResponse) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{29}
}

type ListQueueDispositionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueId       string                 `protobuf:"bytes,1,opt,name=queue_id,json=queueId,proto3" json:"queue_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueueDispositionsRequest) Reset() {
	*x = ListQueueDispositionsRequest{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueueDispositionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueueDispositionsRequest) ProtoMessage() {}

func (x *ListQueueDispositionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueueDispositionsRequest.ProtoReflect.Descriptor instead.
func (*ListQueueDispositionsRequest) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{30}
}

func (x *ListQueueDispositionsRequest) GetQueueId() string {
	if x != nil {
		return x.QueueId
	}
	return ""
}

type ListQueueDispositionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dispositions  []*Disposition         `protobuf:"bytes,1,rep,name=dispositions,proto3" json:"dispositions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueueDispositionsResponse) Reset() {
	*x = ListQueueDispositionsResponse{}
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueueDispositionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueueDispositionsResponse) ProtoMessage() {}

func (x *ListQueueDispositionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_task_router_v1_task_router_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueueDispositionsResponse.ProtoReflect.Descriptor instead.
func (*ListQueueDispositionsResponse) Descriptor() ([]byte, []int) {
	return file_task_router_v1_task_router_admin_proto_rawDescGZIP(), []int{31}
}

func (x *ListQueueDispositionsResponse) GetDispositions() []*Disposition {
	if x != nil {
		return x.Dispositions
	}
	return nil
}

var File_task_router_v1_task_router_admin_proto protoreflect.FileDescriptor

const file_task_router_v1_task_router_admin_proto_rawDesc = "" +
	"\n" +
	"&task-router/v1/task_router_admin.proto\x12\rtaskrouter.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"]\n" +
	"\x05Queue\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\tR\aqueueId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"`\n" +
	"\vStatusEntry\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x96\x01\n" +
	"\x13AttributeDefinition\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.taskrouter.v1.AttributeTypeR\x04type\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"1\n" +
	"\x14RegisterQueueRequest\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\tR\aqueueId\"\x13\n" +
	"\x11ListQueuesRequest\"B\n" +
	"\x12ListQueuesResponse\x12,\n" +
	"\x06queues\x18\x01 \x03(\v2\x14.taskrouter.v1.QueueR\x06queues\",\n" +
	"\x0fGetQueueRequest\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\tR\aqueueId\"h\n" +
	"\x10GetQueueResponse\x12*\n" +
	"\x05queue\x18\x01 \x01(\v2\x14.taskrouter.v1.QueueR\x05queue\x12(\n" +
	"\x10member_agent_ids\x18\x02 \x03(\tR\x0ememberAgentIds\"/\n" +
	"\x12RemoveQueueRequest\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\tR\aqueueId\"\x15\n" +
	"\x13RemoveQueueResponse\"/\n" +
	"\x15RegisterStatusRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x15\n" +
	"\x13ListStatusesRequest\"N\n" +
	"\x14ListStatusesResponse\x126\n" +
	"\bstatuses\x18\x01 \x03(\v2\x1a.taskrouter.v1.StatusEntryR\bstatuses\"-\n" +
	"\x13RemoveStatusRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x16\n" +
	"\x14RemoveStatusResponse\"`\n" +
	"\x18RegisterAttributeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.taskrouter.v1.AttributeTypeR\x04type\"\x17\n" +
	"\x15ListAttributesRequest\"\\\n" +
	"\x16ListAttributesResponse\x12B\n" +
	"\n" +
	"attributes\x18\x01 \x03(\v2\".taskrouter.v1.AttributeDefinitionR\n" +
	"attributes\")\n" +
	"\x13GetAttributeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x86\x01\n" +
	"\x14GetAttributeResponse\x12@\n" +
	"\tattribute\x18\x01 \x01(\v2\".taskrouter.v1.AttributeDefinitionR\tattribute\x12,\n" +
	"\x12assigned_agent_ids\x18\x02 \x03(\tR\x10assignedAgentIds\",\n" +
	"\x16RemoveAttributeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x19\n" +
	"\x17RemoveAttributeResponse\"\x83\x01\n" +
	"\vDisposition\x12%\n" +
	"\x0edisposition_id\x18\x01 \x01(\tR\rdispositionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"W\n" +
	"\x1aRegisterDispositionRequest\x12%\n" +
	"\x0edisposition_id\x18\x01 \x01(\tR\rdispositionId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\x19\n" +
	"\x17ListDispositionsRequest\"Z\n" +
	"\x18ListDispositionsResponse\x12>\n" +
	"\fdispositions\x18\x01 \x03(\v2\x1a.taskrouter.v1.DispositionR\fdispositions\"A\n" +
	"\x18RemoveDispositionRequest\x12%\n" +
	"\x0edisposition_id\x18\x01 \x01(\tR\rdispositionId\"\x1b\n" +
	"\x19RemoveDispositionResponse\"g\n" +
	"!AssociateQueueDispositionsRequest\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\tR\aqueueId\x12'\n" +
	"\x0fdisposition_ids\x18\x02 \x03(\tR\x0edispositionIds\"$\n" +
	"\"AssociateQueueDispositionsResponse\"9\n" +
	"\x1cListQueueDispositionsRequest\x12\x19\n" +
	"\bqueue_id\x18\x01 \x01(\tR\aqueueId\"_\n" +
	"\x1dListQueueDispositionsResponse\x12>\n" +
	"\fdispositions\x18\x01 \x03(\v2\x1a.taskrouter.v1.DispositionR\fdispositions*g\n" +
	"\rAttributeType\x12\x1e\n" +
	"\x1aATTRIBUTE_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16ATTRIBUTE_TYPE_NUMERIC\x10\x01\x12\x1a\n" +
	"\x16ATTRIBUTE_TYPE_BOOLEAN\x10\x022\xc9\x10\n" +
	"\x16TaskRouterAdminService\x12g\n" +
	"\rRegisterQueue\x12#.taskrouter.v1.RegisterQueueRequest\x1a\x14.taskrouter.v1.Queue\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/v1/admin/queues\x12k\n" +
	"\n" +
	"ListQueues\x12 .taskrouter.v1.ListQueuesRequest\x1a!.taskrouter.v1.ListQueuesResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/v1/admin/queues\x12p\n" +
	"\bGetQueue\x12\x1e.taskrouter.v1.GetQueueRequest\x1a\x1f.taskrouter.v1.GetQueueResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/admin/queues/{queue_id}\x12y\n" +
	"\vRemoveQueue\x12!.taskrouter.v1.RemoveQueueRequest\x1a\".taskrouter.v1.RemoveQueueResponse\"#\x82\xd3\xe4\x93\x02\x1d*\x1b/v1/admin/queues/{queue_id}\x12q\n" +
	"\x0eRegisterStatus\x12$.taskrouter.v1.RegisterStatusRequest\x1a\x1a.taskrouter.v1.StatusEntry\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/v1/admin/statuses\x12s\n" +
	"\fListStatuses\x12\".taskrouter.v1.ListStatusesRequest\x1a#.taskrouter.v1.ListStatusesResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/v1/admin/statuses\x12|\n" +
	"\fRemoveStatus\x12\".taskrouter.v1.RemoveStatusRequest\x1a#.taskrouter.v1.RemoveStatusResponse\"#\x82\xd3\xe4\x93\x02\x1d*\x1b/v1/admin/statuses/{status}\x12\x81\x01\n" +
	"\x11RegisterAttribute\x12'.taskrouter.v1.RegisterAttributeRequest\x1a\".taskrouter.v1.AttributeDefinition\"\x1f\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/admin/attributes\x12{\n" +
	"\x0eListAttributes\x12$.taskrouter.v1.ListAttributesRequest\x1a%.taskrouter.v1.ListAttributesResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/admin/attributes\x12|\n" +
	"\fGetAttribute\x12\".taskrouter.v1.GetAttributeRequest\x1a#.taskrouter.v1.GetAttributeResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/v1/admin/attributes/{name}\x12\x85\x01\n" +
	"\x0fRemoveAttribute\x12%.taskrouter.v1.RemoveAttributeRequest\x1a&.taskrouter.v1.RemoveAttributeResponse\"#\x82\xd3\xe4\x93\x02\x1d*\x1b/v1/admin/attributes/{name}\x12\x7f\n" +
	"\x13RegisterDisposition\x12).taskrouter.v1.RegisterDispositionRequest\x1a\x1a.taskrouter.v1.Disposition\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/v1/admin/dispositions\x12\x83\x01\n" +
	"\x10ListDispositions\x12&.taskrouter.v1.ListDispositionsRequest\x1a'.taskrouter.v1.ListDispositionsResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/v1/admin/dispositions\x12\x97\x01\n" +
	"\x11RemoveDisposition\x12'.taskrouter.v1.RemoveDispositionRequest\x1a(.taskrouter.v1.RemoveDispositionResponse\"/\x82\xd3\xe4\x93\x02)*'/v1/admin/dispositions/{disposition_id}\x12\xb6\x01\n" +
	"\x1aAssociateQueueDispositions\x120.taskrouter.v1.AssociateQueueDispositionsRequest\x1a1.taskrouter.v1.AssociateQueueDispositionsResponse\"3\x82\xd3\xe4\x93\x02-:\x01*\"(/v1/admin/queues/{queue_id}/dispositions\x12\xa4\x01\n" +
	"\x15ListQueueDispositions\x12+.taskrouter.v1.ListQueueDispositionsRequest\x1a,.taskrouter.v1.ListQueueDispositionsResponse\"0\x82\xd3\xe4\x93\x02*\x12(/v1/admin/queues/{queue_id}/dispositionsBRZPgithub.com/thecraftynoob/ProjectPoutine/pkg/genproto/task-router/v1;taskrouterv1b\x06proto3"

var (
	file_task_router_v1_task_router_admin_proto_rawDescOnce sync.Once
	file_task_router_v1_task_router_admin_proto_rawDescData []byte
)

func file_task_router_v1_task_router_admin_proto_rawDescGZIP() []byte {
	file_task_router_v1_task_router_admin_proto_rawDescOnce.Do(func() {
		file_task_router_v1_task_router_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_router_v1_task_router_admin_proto_rawDesc), len(file_task_router_v1_task_router_admin_proto_rawDesc)))
	})
	return file_task_router_v1_task_router_admin_proto_rawDescData
}

var file_task_router_v1_task_router_admin_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_task_router_v1_task_router_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_task_router_v1_task_router_admin_proto_goTypes = []any{
	(AttributeType)(0),                         // 0: taskrouter.v1.AttributeType
	(*Queue)(nil),                              // 1: taskrouter.v1.Queue
	(*StatusEntry)(nil),                        // 2: taskrouter.v1.StatusEntry
	(*AttributeDefinition)(nil),                // 3: taskrouter.v1.AttributeDefinition
	(*RegisterQueueRequest)(nil),               // 4: taskrouter.v1.RegisterQueueRequest
	(*ListQueuesRequest)(nil),                  // 5: taskrouter.v1.ListQueuesRequest
	(*ListQueuesResponse)(nil),                 // 6: taskrouter.v1.ListQueuesResponse
	(*GetQueueRequest)(nil),                    // 7: taskrouter.v1.GetQueueRequest
	(*GetQueueResponse)(nil),                   // 8: taskrouter.v1.GetQueueResponse
	(*RemoveQueueRequest)(nil),                 // 9: taskrouter.v1.RemoveQueueRequest
	(*RemoveQueueResponse)(nil),                // 10: taskrouter.v1.RemoveQueueResponse
	(*RegisterStatusRequest)(nil),              // 11: taskrouter.v1.RegisterStatusRequest
	(*ListStatusesRequest)(nil),                // 12: taskrouter.v1.ListStatusesRequest
	(*ListStatusesResponse)(nil),               // 13: taskrouter.v1.ListStatusesResponse
	(*RemoveStatusRequest)(nil),                // 14: taskrouter.v1.RemoveStatusRequest
	(*RemoveStatusResponse)(nil),               // 15: taskrouter.v1.RemoveStatusResponse
	(*RegisterAttributeRequest)(nil),           // 16: taskrouter.v1.RegisterAttributeRequest
	(*ListAttributesRequest)(nil),              // 17: taskrouter.v1.ListAttributesRequest
	(*ListAttributesResponse)(nil),             // 18: taskrouter.v1.ListAttributesResponse
	(*GetAttributeRequest)(nil),                // 19: taskrouter.v1.GetAttributeRequest
	(*GetAttributeResponse)(nil),               // 20: taskrouter.v1.GetAttributeResponse
	(*RemoveAttributeRequest)(nil),             // 21: taskrouter.v1.RemoveAttributeRequest
	(*RemoveAttributeResponse)(nil),            // 22: taskrouter.v1.RemoveAttributeResponse
	(*Disposition)(nil),                        // 23: taskrouter.v1.Disposition
	(*RegisterDispositionRequest)(nil),         // 24: taskrouter.v1.RegisterDispositionRequest
	(*ListDispositionsRequest)(nil),            // 25: taskrouter.v1.ListDispositionsRequest
	(*ListDispositionsResponse)(nil),           // 26: taskrouter.v1.ListDispositionsResponse
	(*RemoveDispositionRequest)(nil),           // 27: taskrouter.v1.RemoveDispositionRequest
	(*RemoveDispositionResponse)(nil),          // 28: taskrouter.v1.RemoveDispositionResponse
	(*AssociateQueueDispositionsRequest)(nil),  // 29: taskrouter.v1.AssociateQueueDispositionsRequest
	(*AssociateQueueDispositionsResponse)(nil), // 30: taskrouter.v1.AssociateQueueDispositionsResponse
	(*ListQueueDispositionsRequest)(nil),       // 31: taskrouter.v1.ListQueueDispositionsRequest
	(*ListQueueDispositionsResponse)(nil),      // 32: taskrouter.v1.ListQueueDispositionsResponse
	(*timestamppb.Timestamp)(nil),              // 33: google.protobuf.Timestamp
}
var file_task_router_v1_task_router_admin_proto_depIdxs = []int32{
	33, // 0: taskrouter.v1.Queue.created_at:type_name -> google.protobuf.Timestamp
	33, // 1: taskrouter.v1.StatusEntry.created_at:type_name -> google.protobuf.Timestamp
	0,  // 2: taskrouter.v1.AttributeDefinition.type:type_name -> taskrouter.v1.AttributeType
	33, // 3: taskrouter.v1.AttributeDefinition.created_at:type_name -> google.protobuf.Timestamp
	1,  // 4: taskrouter.v1.ListQueuesResponse.queues:type_name -> taskrouter.v1.Queue
	1,  // 5: taskrouter.v1.GetQueueResponse.queue:type_name -> taskrouter.v1.Queue
	2,  // 6: taskrouter.v1.ListStatusesResponse.statuses:type_name -> taskrouter.v1.StatusEntry
	0,  // 7: taskrouter.v1.RegisterAttributeRequest.type:type_name -> taskrouter.v1.AttributeType
	3,  // 8: taskrouter.v1.ListAttributesResponse.attributes:type_name -> taskrouter.v1.AttributeDefinition
	3,  // 9: taskrouter.v1.GetAttributeResponse.attribute:type_name -> taskrouter.v1.AttributeDefinition
	33, // 10: taskrouter.v1.Disposition.created_at:type_name -> google.protobuf.Timestamp
	23, // 11: taskrouter.v1.ListDispositionsResponse.dispositions:type_name -> taskrouter.v1.Disposition
	23, // 12: taskrouter.v1.ListQueueDispositionsResponse.dispositions:type_name -> taskrouter.v1.Disposition
	4,  // 13: taskrouter.v1.TaskRouterAdminService.RegisterQueue:input_type -> taskrouter.v1.RegisterQueueRequest
	5,  // 14: taskrouter.v1.TaskRouterAdminService.ListQueues:input_type -> taskrouter.v1.ListQueuesRequest
	7,  // 15: taskrouter.v1.TaskRouterAdminService.GetQueue:input_type -> taskrouter.v1.GetQueueRequest
	9,  // 16: taskrouter.v1.TaskRouterAdminService.RemoveQueue:input_type -> taskrouter.v1.RemoveQueueRequest
	11, // 17: taskrouter.v1.TaskRouterAdminService.RegisterStatus:input_type -> taskrouter.v1.RegisterStatusRequest
	12, // 18: taskrouter.v1.TaskRouterAdminService.ListStatuses:input_type -> taskrouter.v1.ListStatusesRequest
	14, // 19: taskrouter.v1.TaskRouterAdminService.RemoveStatus:input_type -> taskrouter.v1.RemoveStatusRequest
	16, // 20: taskrouter.v1.TaskRouterAdminService.RegisterAttribute:input_type -> taskrouter.v1.RegisterAttributeRequest
	17, // 21: taskrouter.v1.TaskRouterAdminService.ListAttributes:input_type -> taskrouter.v1.ListAttributesRequest
	19, // 22: taskrouter.v1.TaskRouterAdminService.GetAttribute:input_type -> taskrouter.v1.GetAttributeRequest
	21, // 23: taskrouter.v1.TaskRouterAdminService.RemoveAttribute:input_type -> taskrouter.v1.RemoveAttributeRequest
	24, // 24: taskrouter.v1.TaskRouterAdminService.RegisterDisposition:input_type -> taskrouter.v1.RegisterDispositionRequest
	25, // 25: taskrouter.v1.TaskRouterAdminService.ListDispositions:input_type -> taskrouter.v1.ListDispositionsRequest
	27, // 26: taskrouter.v1.TaskRouterAdminService.RemoveDisposition:input_type -> taskrouter.v1.RemoveDispositionRequest
	29, // 27: taskrouter.v1.TaskRouterAdminService.AssociateQueueDispositions:input_type -> taskrouter.v1.AssociateQueueDispositionsRequest
	31, // 28: taskrouter.v1.TaskRouterAdminService.ListQueueDispositions:input_type -> taskrouter.v1.ListQueueDispositionsRequest
	1,  // 29: taskrouter.v1.TaskRouterAdminService.RegisterQueue:output_type -> taskrouter.v1.Queue
	6,  // 30: taskrouter.v1.TaskRouterAdminService.ListQueues:output_type -> taskrouter.v1.ListQueuesResponse
	8,  // 31: taskrouter.v1.TaskRouterAdminService.GetQueue:output_type -> taskrouter.v1.GetQueueResponse
	10, // 32: taskrouter.v1.TaskRouterAdminService.RemoveQueue:output_type -> taskrouter.v1.RemoveQueueResponse
	2,  // 33: taskrouter.v1.TaskRouterAdminService.RegisterStatus:output_type -> taskrouter.v1.StatusEntry
	13, // 34: taskrouter.v1.TaskRouterAdminService.ListStatuses:output_type -> taskrouter.v1.ListStatusesResponse
	15, // 35: taskrouter.v1.TaskRouterAdminService.RemoveStatus:output_type -> taskrouter.v1.RemoveStatusResponse
	3,  // 36: taskrouter.v1.TaskRouterAdminService.RegisterAttribute:output_type -> taskrouter.v1.AttributeDefinition
	18, // 37: taskrouter.v1.TaskRouterAdminService.ListAttributes:output_type -> taskrouter.v1.ListAttributesResponse
	20, // 38: taskrouter.v1.TaskRouterAdminService.GetAttribute:output_type -> taskrouter.v1.GetAttributeResponse
	22, // 39: taskrouter.v1.TaskRouterAdminService.RemoveAttribute:output_type -> taskrouter.v1.RemoveAttributeResponse
	23, // 40: taskrouter.v1.TaskRouterAdminService.RegisterDisposition:output_type -> taskrouter.v1.Disposition
	26, // 41: taskrouter.v1.TaskRouterAdminService.ListDispositions:output_type -> taskrouter.v1.ListDispositionsResponse
	28, // 42: taskrouter.v1.TaskRouterAdminService.RemoveDisposition:output_type -> taskrouter.v1.RemoveDispositionResponse
	30, // 43: taskrouter.v1.TaskRouterAdminService.AssociateQueueDispositions:output_type -> taskrouter.v1.AssociateQueueDispositionsResponse
	32, // 44: taskrouter.v1.TaskRouterAdminService.ListQueueDispositions:output_type -> taskrouter.v1.ListQueueDispositionsResponse
	29, // [29:45] is the sub-list for method output_type
	13, // [13:29] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_task_router_v1_task_router_admin_proto_init() }
func file_task_router_v1_task_router_admin_proto_init() {
	if File_task_router_v1_task_router_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_router_v1_task_router_admin_proto_rawDesc), len(file_task_router_v1_task_router_admin_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_task_router_v1_task_router_admin_proto_goTypes,
		DependencyIndexes: file_task_router_v1_task_router_admin_proto_depIdxs,
		EnumInfos:         file_task_router_v1_task_router_admin_proto_enumTypes,
		MessageInfos:      file_task_router_v1_task_router_admin_proto_msgTypes,
	}.Build()
	File_task_router_v1_task_router_admin_proto = out.File
	file_task_router_v1_task_router_admin_proto_goTypes = nil
	file_task_router_v1_task_router_admin_proto_depIdxs = nil
}
