// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: task-router/v1/task_router.proto

package taskrouterv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TaskRouterService_CreateAgent_FullMethodName            = "/taskrouter.v1.TaskRouterService/CreateAgent"
	TaskRouterService_ListAgents_FullMethodName             = "/taskrouter.v1.TaskRouterService/ListAgents"
	TaskRouterService_GetAgent_FullMethodName               = "/taskrouter.v1.TaskRouterService/GetAgent"
	TaskRouterService_DeleteAgent_FullMethodName            = "/taskrouter.v1.TaskRouterService/DeleteAgent"
	TaskRouterService_SetAgentStatus_FullMethodName         = "/taskrouter.v1.TaskRouterService/SetAgentStatus"
	TaskRouterService_ReplaceAgentCapacity_FullMethodName   = "/taskrouter.v1.TaskRouterService/ReplaceAgentCapacity"
	TaskRouterService_ToggleChannelReady_FullMethodName     = "/taskrouter.v1.TaskRouterService/ToggleChannelReady"
	TaskRouterService_ReplaceAgentQueues_FullMethodName     = "/taskrouter.v1.TaskRouterService/ReplaceAgentQueues"
	TaskRouterService_ReplaceAgentAttributes_FullMethodName = "/taskrouter.v1.TaskRouterService/ReplaceAgentAttributes"
	TaskRouterService_ListAgentPendingOffers_FullMethodName = "/taskrouter.v1.TaskRouterService/ListAgentPendingOffers"
	TaskRouterService_EnqueueTask_FullMethodName            = "/taskrouter.v1.TaskRouterService/EnqueueTask"
	TaskRouterService_ListTasks_FullMethodName              = "/taskrouter.v1.TaskRouterService/ListTasks"
	TaskRouterService_GetTask_FullMethodName                = "/taskrouter.v1.TaskRouterService/GetTask"
	TaskRouterService_CompleteTask_FullMethodName           = "/taskrouter.v1.TaskRouterService/CompleteTask"
	TaskRouterService_AcceptReservation_FullMethodName      = "/taskrouter.v1.TaskRouterService/AcceptReservation"
	TaskRouterService_RejectReservation_FullMethodName      = "/taskrouter.v1.TaskRouterService/RejectReservation"
	TaskRouterService_GetDashboard_FullMethodName           = "/taskrouter.v1.TaskRouterService/GetDashboard"
)

// TaskRouterServiceClient is the client API for TaskRouterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TaskRouterService is the hot-path domain contract for the Task Router
// (TASK_ROUTER_SPECIFICATION.md Sections 3.2-3.4, 3.7): Agent CRUD/
// presence/capacity/queues, Task lifecycle, the Reservation handshake, and
// the aggregate dashboard view.
//
// NOTE: tenant_id is deliberately NOT a field on any message here. Per
// architecture doc Section 1.1, tenant scoping travels as gRPC metadata
// (`x-tenant-id`), injected/validated by pkg/tenantctx — never as an
// in-message field.
//
// NOTE: Section 3.5 ("Real-Time Notification Delivery" / streaming push to
// an Agent Desktop) is explicitly REMOVED from this service's contract per
// the production scoping decision — Task Router only publishes domain
// events to NATS (see internal/events); a future, separate Agent & Presence
// Service milestone is the documented consumer that would relay those to
// connected clients. No streaming/WebSocket RPC is defined here.
type TaskRouterServiceClient interface {
	// CreateAgent provisions a new agent's routing profile. Rejected if the
	// agent ID already exists (atomic uniqueness guarantee, spec Section
	// 5.4 rule 1). The initial status is NOT validated against the Status
	// registry at creation time (spec Section 3.2) — only the status-update
	// capability enforces that.
	CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	// ListAgents enumerates all agents for the tenant.
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	// GetAgent retrieves one agent's full profile.
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*Agent, error)
	// DeleteAgent deprovisions an agent's routing profile. If the agent
	// currently holds a Reserved or Active task, that task is atomically
	// reset to Pending at its original FIFO position and any tied
	// Offered/Accepted reservation is marked Rejected (reason: agent
	// deleted) — spec Section 5.5.
	DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*DeleteAgentResponse, error)
	// SetAgentStatus changes an agent's master presence value. Rejected if
	// the target status is not a registered Status value.
	SetAgentStatus(ctx context.Context, in *SetAgentStatusRequest, opts ...grpc.CallOption) (*Agent, error)
	// ReplaceAgentCapacity fully replaces an agent's per-channel capacity
	// map. Any channel omitted from the input is removed. `active` supplied
	// by the caller is always ignored — a retained channel keeps its live
	// `active` count, a new channel starts at 0.
	ReplaceAgentCapacity(ctx context.Context, in *ReplaceAgentCapacityRequest, opts ...grpc.CallOption) (*Agent, error)
	// ToggleChannelReady flips a single channel's `ready` flag without
	// resending the whole capacity map. If the channel does not yet exist on
	// the agent, it is created with default max=1, interruptible=true.
	ToggleChannelReady(ctx context.Context, in *ToggleChannelReadyRequest, opts ...grpc.CallOption) (*Agent, error)
	// ReplaceAgentQueues fully replaces an agent's queue memberships.
	// Rejected entirely (no partial application) if any queue ID does not
	// exist.
	ReplaceAgentQueues(ctx context.Context, in *ReplaceAgentQueuesRequest, opts ...grpc.CallOption) (*Agent, error)
	// ReplaceAgentAttributes fully replaces an agent's stored attribute
	// values, validated for shape against the Attribute registry. Not used
	// for routing. Emits no event (spec Section 6.2).
	ReplaceAgentAttributes(ctx context.Context, in *ReplaceAgentAttributesRequest, opts ...grpc.CallOption) (*Agent, error)
	// ListAgentPendingOffers returns the agent's currently Offered
	// reservations.
	ListAgentPendingOffers(ctx context.Context, in *ListAgentPendingOffersRequest, opts ...grpc.CallOption) (*ListAgentPendingOffersResponse, error)
	// EnqueueTask submits a new unit of work for routing, creating it in
	// Pending status. Rejected if the queue doesn't exist, an attribute is
	// invalid, or a caller-supplied task ID collides with an existing one.
	EnqueueTask(ctx context.Context, in *EnqueueTaskRequest, opts ...grpc.CallOption) (*Task, error)
	// ListTasks enumerates all tasks for the tenant.
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	// GetTask retrieves one task's current state.
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error)
	// CompleteTask signals that an Active task's work is finished, freeing
	// the assigned agent's capacity. Rejected unless the task is currently
	// Active.
	CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*Task, error)
	// AcceptReservation lets an agent agree to take the offered task.
	// Rejected unless the reservation is currently Offered.
	AcceptReservation(ctx context.Context, in *AcceptReservationRequest, opts ...grpc.CallOption) (*Reservation, error)
	// RejectReservation lets an agent explicitly decline the offered task.
	// Rejected unless the reservation is currently Offered (race-safe
	// re-check). Returns the task to Pending at its original enqueue
	// position and sets the agent's status to the system value
	// "Not Responding".
	RejectReservation(ctx context.Context, in *RejectReservationRequest, opts ...grpc.CallOption) (*Reservation, error)
	// GetDashboard returns all agents (with live assigned-task counts) and
	// all tasks (with current status/assignment) in a single call, for a
	// monitoring display.
	GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardResponse, error)
}

type taskRouterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskRouterServiceClient(cc grpc.ClientConnInterface) TaskRouterServiceClient {
	return &taskRouterServiceClient{cc}
}

func (c *taskRouterServiceClient) CreateAgent(ctx context.Context, in *CreateAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, TaskRouterService_CreateAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterServiceClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, TaskRouterService_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterServiceClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, TaskRouterService_GetAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterServiceClient) DeleteAgent(ctx context.Context, in *DeleteAgentRequest, opts ...grpc.CallOption) (*DeleteAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAgentResponse)
	err := c.cc.Invoke(ctx, TaskRouterService_DeleteAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterServiceClient) SetAgentStatus(ctx context.Context, in *SetAgentStatusRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, TaskRouterService_SetAgentStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterServiceClient) ReplaceAgentCapacity(ctx context.Context, in *ReplaceAgentCapacityRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, TaskRouterService_ReplaceAgentCapacity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterServiceClient) ToggleChannelReady(ctx context.Context, in *ToggleChannelReadyRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, TaskRouterService_ToggleChannelReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterServiceClient) ReplaceAgentQueues(ctx context.Context, in *ReplaceAgentQueuesRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, TaskRouterService_ReplaceAgentQueues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterServiceClient) ReplaceAgentAttributes(ctx context.Context, in *ReplaceAgentAttributesRequest, opts ...grpc.CallOption) (*Agent, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Agent)
	err := c.cc.Invoke(ctx, TaskRouterService_ReplaceAgentAttributes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterServiceClient) ListAgentPendingOffers(ctx context.Context, in *ListAgentPendingOffersRequest, opts ...grpc.CallOption) (*ListAgentPendingOffersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentPendingOffersResponse)
	err := c.cc.Invoke(ctx, TaskRouterService_ListAgentPendingOffers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterServiceClient) EnqueueTask(ctx context.Context, in *EnqueueTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, TaskRouterService_EnqueueTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, TaskRouterService_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, TaskRouterService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterServiceClient) CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, TaskRouterService_CompleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterServiceClient) AcceptReservation(ctx context.Context, in *AcceptReservationRequest, opts ...grpc.CallOption) (*Reservation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reservation)
	err := c.cc.Invoke(ctx, TaskRouterService_AcceptReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterServiceClient) RejectReservation(ctx context.Context, in *RejectReservationRequest, opts ...grpc.CallOption) (*Reservation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Reservation)
	err := c.cc.Invoke(ctx, TaskRouterService_RejectReservation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskRouterServiceClient) GetDashboard(ctx context.Context, in *GetDashboardRequest, opts ...grpc.CallOption) (*GetDashboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDashboardResponse)
	err := c.cc.Invoke(ctx, TaskRouterService_GetDashboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TaskRouterServiceServer is the server API for TaskRouterService service.
// All implementations must embed UnimplementedTaskRouterServiceServer
// for forward compatibility.
//
// TaskRouterService is the hot-path domain contract for the Task Router
// (TASK_ROUTER_SPECIFICATION.md Sections 3.2-3.4, 3.7): Agent CRUD/
// presence/capacity/queues, Task lifecycle, the Reservation handshake, and
// the aggregate dashboard view.
//
// NOTE: tenant_id is deliberately NOT a field on any message here. Per
// architecture doc Section 1.1, tenant scoping travels as gRPC metadata
// (`x-tenant-id`), injected/validated by pkg/tenantctx — never as an
// in-message field.
//
// NOTE: Section 3.5 ("Real-Time Notification Delivery" / streaming push to
// an Agent Desktop) is explicitly REMOVED from this service's contract per
// the production scoping decision — Task Router only publishes domain
// events to NATS (see internal/events); a future, separate Agent & Presence
// Service milestone is the documented consumer that would relay those to
// connected clients. No streaming/WebSocket RPC is defined here.
type TaskRouterServiceServer interface {
	// CreateAgent provisions a new agent's routing profile. Rejected if the
	// agent ID already exists (atomic uniqueness guarantee, spec Section
	// 5.4 rule 1). The initial status is NOT validated against the Status
	// registry at creation time (spec Section 3.2) — only the status-update
	// capability enforces that.
	CreateAgent(context.Context, *CreateAgentRequest) (*Agent, error)
	// ListAgents enumerates all agents for the tenant.
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	// GetAgent retrieves one agent's full profile.
	GetAgent(context.Context, *GetAgentRequest) (*Agent, error)
	// DeleteAgent deprovisions an agent's routing profile. If the agent
	// currently holds a Reserved or Active task, that task is atomically
	// reset to Pending at its original FIFO position and any tied
	// Offered/Accepted reservation is marked Rejected (reason: agent
	// deleted) — spec Section 5.5.
	DeleteAgent(context.Context, *DeleteAgentRequest) (*DeleteAgentResponse, error)
	// SetAgentStatus changes an agent's master presence value. Rejected if
	// the target status is not a registered Status value.
	SetAgentStatus(context.Context, *SetAgentStatusRequest) (*Agent, error)
	// ReplaceAgentCapacity fully replaces an agent's per-channel capacity
	// map. Any channel omitted from the input is removed. `active` supplied
	// by the caller is always ignored — a retained channel keeps its live
	// `active` count, a new channel starts at 0.
	ReplaceAgentCapacity(context.Context, *ReplaceAgentCapacityRequest) (*Agent, error)
	// ToggleChannelReady flips a single channel's `ready` flag without
	// resending the whole capacity map. If the channel does not yet exist on
	// the agent, it is created with default max=1, interruptible=true.
	ToggleChannelReady(context.Context, *ToggleChannelReadyRequest) (*Agent, error)
	// ReplaceAgentQueues fully replaces an agent's queue memberships.
	// Rejected entirely (no partial application) if any queue ID does not
	// exist.
	ReplaceAgentQueues(context.Context, *ReplaceAgentQueuesRequest) (*Agent, error)
	// ReplaceAgentAttributes fully replaces an agent's stored attribute
	// values, validated for shape against the Attribute registry. Not used
	// for routing. Emits no event (spec Section 6.2).
	ReplaceAgentAttributes(context.Context, *ReplaceAgentAttributesRequest) (*Agent, error)
	// ListAgentPendingOffers returns the agent's currently Offered
	// reservations.
	ListAgentPendingOffers(context.Context, *ListAgentPendingOffersRequest) (*ListAgentPendingOffersResponse, error)
	// EnqueueTask submits a new unit of work for routing, creating it in
	// Pending status. Rejected if the queue doesn't exist, an attribute is
	// invalid, or a caller-supplied task ID collides with an existing one.
	EnqueueTask(context.Context, *EnqueueTaskRequest) (*Task, error)
	// ListTasks enumerates all tasks for the tenant.
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	// GetTask retrieves one task's current state.
	GetTask(context.Context, *GetTaskRequest) (*Task, error)
	// CompleteTask signals that an Active task's work is finished, freeing
	// the assigned agent's capacity. Rejected unless the task is currently
	// Active.
	CompleteTask(context.Context, *CompleteTaskRequest) (*Task, error)
	// AcceptReservation lets an agent agree to take the offered task.
	// Rejected unless the reservation is currently Offered.
	AcceptReservation(context.Context, *AcceptReservationRequest) (*Reservation, error)
	// RejectReservation lets an agent explicitly decline the offered task.
	// Rejected unless the reservation is currently Offered (race-safe
	// re-check). Returns the task to Pending at its original enqueue
	// position and sets the agent's status to the system value
	// "Not Responding".
	RejectReservation(context.Context, *RejectReservationRequest) (*Reservation, error)
	// GetDashboard returns all agents (with live assigned-task counts) and
	// all tasks (with current status/assignment) in a single call, for a
	// monitoring display.
	GetDashboard(context.Context, *GetDashboardRequest) (*GetDashboardResponse, error)
	mustEmbedUnimplementedTaskRouterServiceServer()
}

// UnimplementedTaskRouterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTaskRouterServiceServer struct{}

func (UnimplementedTaskRouterServiceServer) CreateAgent(context.Context, *CreateAgentRequest) (*Agent, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAgent not implemented")
}
func (UnimplementedTaskRouterServiceServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedTaskRouterServiceServer) GetAgent(context.Context, *GetAgentRequest) (*Agent, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedTaskRouterServiceServer) DeleteAgent(context.Context, *DeleteAgentRequest) (*DeleteAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAgent not implemented")
}
func (UnimplementedTaskRouterServiceServer) SetAgentStatus(context.Context, *SetAgentStatusRequest) (*Agent, error) {
	return nil, status.Error(codes.Unimplemented, "method SetAgentStatus not implemented")
}
func (UnimplementedTaskRouterServiceServer) ReplaceAgentCapacity(context.Context, *ReplaceAgentCapacityRequest) (*Agent, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplaceAgentCapacity not implemented")
}
func (UnimplementedTaskRouterServiceServer) ToggleChannelReady(context.Context, *ToggleChannelReadyRequest) (*Agent, error) {
	return nil, status.Error(codes.Unimplemented, "method ToggleChannelReady not implemented")
}
func (UnimplementedTaskRouterServiceServer) ReplaceAgentQueues(context.Context, *ReplaceAgentQueuesRequest) (*Agent, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplaceAgentQueues not implemented")
}
func (UnimplementedTaskRouterServiceServer) ReplaceAgentAttributes(context.Context, *ReplaceAgentAttributesRequest) (*Agent, error) {
	return nil, status.Error(codes.Unimplemented, "method ReplaceAgentAttributes not implemented")
}
func (UnimplementedTaskRouterServiceServer) ListAgentPendingOffers(context.Context, *ListAgentPendingOffersRequest) (*ListAgentPendingOffersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgentPendingOffers not implemented")
}
func (UnimplementedTaskRouterServiceServer) EnqueueTask(context.Context, *EnqueueTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method EnqueueTask not implemented")
}
func (UnimplementedTaskRouterServiceServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedTaskRouterServiceServer) GetTask(context.Context, *GetTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTaskRouterServiceServer) CompleteTask(context.Context, *CompleteTaskRequest) (*Task, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteTask not implemented")
}
func (UnimplementedTaskRouterServiceServer) AcceptReservation(context.Context, *AcceptReservationRequest) (*Reservation, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptReservation not implemented")
}
func (UnimplementedTaskRouterServiceServer) RejectReservation(context.Context, *RejectReservationRequest) (*Reservation, error) {
	return nil, status.Error(codes.Unimplemented, "method RejectReservation not implemented")
}
func (UnimplementedTaskRouterServiceServer) GetDashboard(context.Context, *GetDashboardRequest) (*GetDashboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDashboard not implemented")
}
func (UnimplementedTaskRouterServiceServer) mustEmbedUnimplementedTaskRouterServiceServer() {}
func (UnimplementedTaskRouterServiceServer) testEmbeddedByValue()                           {}

// UnsafeTaskRouterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskRouterServiceServer will
// result in compilation errors.
type UnsafeTaskRouterServiceServer interface {
	mustEmbedUnimplementedTaskRouterServiceServer()
}

func RegisterTaskRouterServiceServer(s grpc.ServiceRegistrar, srv TaskRouterServiceServer) {
	// If the following call panics, it indicates UnimplementedTaskRouterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TaskRouterService_ServiceDesc, srv)
}

func _TaskRouterService_CreateAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterServiceServer).CreateAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterService_CreateAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterServiceServer).CreateAgent(ctx, req.(*CreateAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterService_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterServiceServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterService_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterServiceServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterService_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterServiceServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterService_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterServiceServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterService_DeleteAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterServiceServer).DeleteAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterService_DeleteAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterServiceServer).DeleteAgent(ctx, req.(*DeleteAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterService_SetAgentStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetAgentStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterServiceServer).SetAgentStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterService_SetAgentStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterServiceServer).SetAgentStatus(ctx, req.(*SetAgentStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterService_ReplaceAgentCapacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceAgentCapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterServiceServer).ReplaceAgentCapacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterService_ReplaceAgentCapacity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterServiceServer).ReplaceAgentCapacity(ctx, req.(*ReplaceAgentCapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterService_ToggleChannelReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ToggleChannelReadyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterServiceServer).ToggleChannelReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterService_ToggleChannelReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterServiceServer).ToggleChannelReady(ctx, req.(*ToggleChannelReadyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterService_ReplaceAgentQueues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceAgentQueuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterServiceServer).ReplaceAgentQueues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterService_ReplaceAgentQueues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterServiceServer).ReplaceAgentQueues(ctx, req.(*ReplaceAgentQueuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterService_ReplaceAgentAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplaceAgentAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterServiceServer).ReplaceAgentAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterService_ReplaceAgentAttributes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterServiceServer).ReplaceAgentAttributes(ctx, req.(*ReplaceAgentAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterService_ListAgentPendingOffers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentPendingOffersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterServiceServer).ListAgentPendingOffers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterService_ListAgentPendingOffers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterServiceServer).ListAgentPendingOffers(ctx, req.(*ListAgentPendingOffersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterService_EnqueueTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterServiceServer).EnqueueTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterService_EnqueueTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterServiceServer).EnqueueTask(ctx, req.(*EnqueueTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterService_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterServiceServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterService_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterServiceServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterService_CompleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterServiceServer).CompleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterService_CompleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterServiceServer).CompleteTask(ctx, req.(*CompleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterService_AcceptReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterServiceServer).AcceptReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterService_AcceptReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterServiceServer).AcceptReservation(ctx, req.(*AcceptReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterService_RejectReservation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RejectReservationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterServiceServer).RejectReservation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterService_RejectReservation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterServiceServer).RejectReservation(ctx, req.(*RejectReservationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskRouterService_GetDashboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDashboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskRouterServiceServer).GetDashboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskRouterService_GetDashboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskRouterServiceServer).GetDashboard(ctx, req.(*GetDashboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TaskRouterService_ServiceDesc is the grpc.ServiceDesc for TaskRouterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskRouterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "taskrouter.v1.TaskRouterService",
	HandlerType: (*TaskRouterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAgent",
			Handler:    _TaskRouterService_CreateAgent_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _TaskRouterService_ListAgents_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _TaskRouterService_GetAgent_Handler,
		},
		{
			MethodName: "DeleteAgent",
			Handler:    _TaskRouterService_DeleteAgent_Handler,
		},
		{
			MethodName: "SetAgentStatus",
			Handler:    _TaskRouterService_SetAgentStatus_Handler,
		},
		{
			MethodName: "ReplaceAgentCapacity",
			Handler:    _TaskRouterService_ReplaceAgentCapacity_Handler,
		},
		{
			MethodName: "ToggleChannelReady",
			Handler:    _TaskRouterService_ToggleChannelReady_Handler,
		},
		{
			MethodName: "ReplaceAgentQueues",
			Handler:    _TaskRouterService_ReplaceAgentQueues_Handler,
		},
		{
			MethodName: "ReplaceAgentAttributes",
			Handler:    _TaskRouterService_ReplaceAgentAttributes_Handler,
		},
		{
			MethodName: "ListAgentPendingOffers",
			Handler:    _TaskRouterService_ListAgentPendingOffers_Handler,
		},
		{
			MethodName: "EnqueueTask",
			Handler:    _TaskRouterService_EnqueueTask_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _TaskRouterService_ListTasks_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TaskRouterService_GetTask_Handler,
		},
		{
			MethodName: "CompleteTask",
			Handler:    _TaskRouterService_CompleteTask_Handler,
		},
		{
			MethodName: "AcceptReservation",
			Handler:    _TaskRouterService_AcceptReservation_Handler,
		},
		{
			MethodName: "RejectReservation",
			Handler:    _TaskRouterService_RejectReservation_Handler,
		},
		{
			MethodName: "GetDashboard",
			Handler:    _TaskRouterService_GetDashboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "task-router/v1/task_router.proto",
}
