// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: tenant-identity/v1/tenant_identity.proto

package tenantidentityv1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Tenant mirrors the tenants registry table: id, name, created_at. Not
// itself tenant-scoped data (it IS the tenant registry) -- see
// pgstore/migrations for why no RLS applies to this table.
type Tenant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tenant) Reset() {
	*x = Tenant{}
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tenant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tenant) ProtoMessage() {}

func (x *Tenant) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tenant.ProtoReflect.Descriptor instead.
func (*Tenant) Descriptor() ([]byte, []int) {
	return file_tenant_identity_v1_tenant_identity_proto_rawDescGZIP(), []int{0}
}

func (x *Tenant) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Tenant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tenant) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_identity_v1_tenant_identity_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantRequest) Reset() {
	*x = GetTenantRequest{}
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantRequest) ProtoMessage() {}

func (x *GetTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantRequest.ProtoReflect.Descriptor instead.
func (*GetTenantRequest) Descriptor() ([]byte, []int) {
	return file_tenant_identity_v1_tenant_identity_proto_rawDescGZIP(), []int{2}
}

func (x *GetTenantRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type ListTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsRequest) Reset() {
	*x = ListTenantsRequest{}
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsRequest) ProtoMessage() {}

func (x *ListTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantsRequest) Descriptor() ([]byte, []int) {
	return file_tenant_identity_v1_tenant_identity_proto_rawDescGZIP(), []int{3}
}

type ListTenantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tenants       []*Tenant              `protobuf:"bytes,1,rep,name=tenants,proto3" json:"tenants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsResponse) Reset() {
	*x = ListTenantsResponse{}
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsResponse) ProtoMessage() {}

func (x *ListTenantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsResponse.ProtoReflect.Descriptor instead.
func (*ListTenantsResponse) Descriptor() ([]byte, []int) {
	return file_tenant_identity_v1_tenant_identity_proto_rawDescGZIP(), []int{4}
}

func (x *ListTenantsResponse) GetTenants() []*Tenant {
	if x != nil {
		return x.Tenants
	}
	return nil
}

// User mirrors one tenant-scoped identity record: username, roles (a
// simple set of string tags -- not a policy engine), created_at. Never
// carries the password hash outward.
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Username      string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_tenant_identity_v1_tenant_identity_proto_rawDescGZIP(), []int{5}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *User) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateUserRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Explicit field -- see file-level note on why CreateUser doesn't rely
	// on x-tenant-id metadata.
	TenantId      string   `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Username      string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Roles         []string `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_tenant_identity_v1_tenant_identity_proto_rawDescGZIP(), []int{6}
}

func (x *CreateUserRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateUserRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Explicit field -- the caller has no token yet; this call is how one
	// is obtained.
	TenantId      string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Username      string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_tenant_identity_v1_tenant_identity_proto_rawDescGZIP(), []int{7}
}

func (x *LoginRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LoginRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signed, short-lived JWT (RS256/ES256; see internal/authn) carrying
	// `tid`, `sub`, and `roles` claims, shaped for pkg/jwtauth.Verifier and
	// pkg/tenantctx's eventual future consumption.
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_tenant_identity_v1_tenant_identity_proto_rawDescGZIP(), []int{8}
}

func (x *LoginResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *LoginResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_tenant_identity_v1_tenant_identity_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_tenant_identity_v1_tenant_identity_proto_rawDescGZIP(), []int{10}
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_tenant_identity_v1_tenant_identity_proto_rawDescGZIP(), []int{11}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

type IssueServiceTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The tenant the resulting token should be scoped to (`tid` claim). A
	// service call always acts within some tenant-scoped operation, so this
	// is always required -- there is no cross-tenant service token.
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Identifies the calling service for the `sub` claim (e.g.
	// "task-router", "agent-presence") -- diagnostics/audit only, not part
	// of the trust decision itself (the shared_secret is).
	CallerService string `protobuf:"bytes,2,opt,name=caller_service,json=callerService,proto3" json:"caller_service,omitempty"`
	// The shared service credential, sourced from the same Kubernetes
	// Secret (ccaas-service-credential) on both the caller and this
	// service. Deliberately NOT a per-service username/password -- see this
	// RPC's file-level doc comment for the explicit scoping rationale.
	SharedSecret  string `protobuf:"bytes,3,opt,name=shared_secret,json=sharedSecret,proto3" json:"shared_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueServiceTokenRequest) Reset() {
	*x = IssueServiceTokenRequest{}
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueServiceTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueServiceTokenRequest) ProtoMessage() {}

func (x *IssueServiceTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueServiceTokenRequest.ProtoReflect.Descriptor instead.
func (*IssueServiceTokenRequest) Descriptor() ([]byte, []int) {
	return file_tenant_identity_v1_tenant_identity_proto_rawDescGZIP(), []int{12}
}

func (x *IssueServiceTokenRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IssueServiceTokenRequest) GetCallerService() string {
	if x != nil {
		return x.CallerService
	}
	return ""
}

func (x *IssueServiceTokenRequest) GetSharedSecret() string {
	if x != nil {
		return x.SharedSecret
	}
	return ""
}

type IssueServiceTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Signed, short-lived JWT -- same shape as LoginResponse.token.
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueServiceTokenResponse) Reset() {
	*x = IssueServiceTokenResponse{}
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueServiceTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueServiceTokenResponse) ProtoMessage() {}

func (x *IssueServiceTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tenant_identity_v1_tenant_identity_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueServiceTokenResponse.ProtoReflect.Descriptor instead.
func (*IssueServiceTokenResponse) Descriptor() ([]byte, []int) {
	return file_tenant_identity_v1_tenant_identity_proto_rawDescGZIP(), []int{13}
}

func (x *IssueServiceTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *IssueServiceTokenResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_tenant_identity_v1_tenant_identity_proto protoreflect.FileDescriptor

const file_tenant_identity_v1_tenant_identity_proto_rawDesc = "" +
	"\n" +
	"(tenant-identity/v1/tenant_identity.proto\x12\x11tenantidentity.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"t\n" +
	"\x06Tenant\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\")\n" +
	"\x13CreateTenantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x10GetTenantRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"\x14\n" +
	"\x12ListTenantsRequest\"J\n" +
	"\x13ListTenantsResponse\x123\n" +
	"\atenants\x18\x01 \x03(\v2\x19.tenantidentity.v1.TenantR\atenants\"\xa9\x01\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"~\n" +
	"\x11CreateUserRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\"c\n" +
	"\fLoginRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"`\n" +
	"\rLoginResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\")\n" +
	"\x0eGetUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"\x12\n" +
	"\x10ListUsersRequest\"B\n" +
	"\x11ListUsersResponse\x12-\n" +
	"\x05users\x18\x01 \x03(\v2\x17.tenantidentity.v1.UserR\x05users\"\x83\x01\n" +
	"\x18IssueServiceTokenRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12%\n" +
	"\x0ecaller_service\x18\x02 \x01(\tR\rcallerService\x12#\n" +
	"\rshared_secret\x18\x03 \x01(\tR\fsharedSecret\"l\n" +
	"\x19IssueServiceTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt2\xdb\x02\n" +
	"\rTenantService\x12i\n" +
	"\fCreateTenant\x12&.tenantidentity.v1.CreateTenantRequest\x1a\x19.tenantidentity.v1.Tenant\"\x16\x82\xd3\xe4\x93\x02\x10:\x01*\"\v/v1/tenants\x12l\n" +
	"\tGetTenant\x12#.tenantidentity.v1.GetTenantRequest\x1a\x19.tenantidentity.v1.Tenant\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/v1/tenants/{tenant_id}\x12q\n" +
	"\vListTenants\x12%.tenantidentity.v1.ListTenantsRequest\x1a&.tenantidentity.v1.ListTenantsResponse\"\x13\x82\xd3\xe4\x93\x02\r\x12\v/v1/tenants2\xae\x04\n" +
	"\x0fIdentityService\x12u\n" +
	"\n" +
	"CreateUser\x12$.tenantidentity.v1.CreateUserRequest\x1a\x17.tenantidentity.v1.User\"(\x82\xd3\xe4\x93\x02\":\x01*\"\x1d/v1/tenants/{tenant_id}/users\x12e\n" +
	"\x05Login\x12\x1f.tenantidentity.v1.LoginRequest\x1a .tenantidentity.v1.LoginResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/v1/auth/login\x12b\n" +
	"\aGetUser\x12!.tenantidentity.v1.GetUserRequest\x1a\x17.tenantidentity.v1.User\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/v1/users/{user_id}\x12i\n" +
	"\tListUsers\x12#.tenantidentity.v1.ListUsersRequest\x1a$.tenantidentity.v1.ListUsersResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/users\x12n\n" +
	"\x11IssueServiceToken\x12+.tenantidentity.v1.IssueServiceTokenRequest\x1a,.tenantidentity.v1.IssueServiceTokenResponseBZZXgithub.com/thecraftynoob/ProjectPoutine/pkg/genproto/tenant-identity/v1;tenantidentityv1b\x06proto3"

var (
	file_tenant_identity_v1_tenant_identity_proto_rawDescOnce sync.Once
	file_tenant_identity_v1_tenant_identity_proto_rawDescData []byte
)

func file_tenant_identity_v1_tenant_identity_proto_rawDescGZIP() []byte {
	file_tenant_identity_v1_tenant_identity_proto_rawDescOnce.Do(func() {
		file_tenant_identity_v1_tenant_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tenant_identity_v1_tenant_identity_proto_rawDesc), len(file_tenant_identity_v1_tenant_identity_proto_rawDesc)))
	})
	return file_tenant_identity_v1_tenant_identity_proto_rawDescData
}

var file_tenant_identity_v1_tenant_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_tenant_identity_v1_tenant_identity_proto_goTypes = []any{
	(*Tenant)(nil),                    // 0: tenantidentity.v1.Tenant
	(*CreateTenantRequest)(nil),       // 1: tenantidentity.v1.CreateTenantRequest
	(*GetTenantRequest)(nil),          // 2: tenantidentity.v1.GetTenantRequest
	(*ListTenantsRequest)(nil),        // 3: tenantidentity.v1.ListTenantsRequest
	(*ListTenantsResponse)(nil),       // 4: tenantidentity.v1.ListTenantsResponse
	(*User)(nil),                      // 5: tenantidentity.v1.User
	(*CreateUserRequest)(nil),         // 6: tenantidentity.v1.CreateUserRequest
	(*LoginRequest)(nil),              // 7: tenantidentity.v1.LoginRequest
	(*LoginResponse)(nil),             // 8: tenantidentity.v1.LoginResponse
	(*GetUserRequest)(nil),            // 9: tenantidentity.v1.GetUserRequest
	(*ListUsersRequest)(nil),          // 10: tenantidentity.v1.ListUsersRequest
	(*ListUsersResponse)(nil),         // 11: tenantidentity.v1.ListUsersResponse
	(*IssueServiceTokenRequest)(nil),  // 12: tenantidentity.v1.IssueServiceTokenRequest
	(*IssueServiceTokenResponse)(nil), // 13: tenantidentity.v1.IssueServiceTokenResponse
	(*timestamppb.Timestamp)(nil),     // 14: google.protobuf.Timestamp
}
var file_tenant_identity_v1_tenant_identity_proto_depIdxs = []int32{
	14, // 0: tenantidentity.v1.Tenant.created_at:type_name -> google.protobuf.Timestamp
	0,  // 1: tenantidentity.v1.ListTenantsResponse.tenants:type_name -> tenantidentity.v1.Tenant
	14, // 2: tenantidentity.v1.User.created_at:type_name -> google.protobuf.Timestamp
	14, // 3: tenantidentity.v1.LoginResponse.expires_at:type_name -> google.protobuf.Timestamp
	5,  // 4: tenantidentity.v1.ListUsersResponse.users:type_name -> tenantidentity.v1.User
	14, // 5: tenantidentity.v1.IssueServiceTokenResponse.expires_at:type_name -> google.protobuf.Timestamp
	1,  // 6: tenantidentity.v1.TenantService.CreateTenant:input_type -> tenantidentity.v1.CreateTenantRequest
	2,  // 7: tenantidentity.v1.TenantService.GetTenant:input_type -> tenantidentity.v1.GetTenantRequest
	3,  // 8: tenantidentity.v1.TenantService.ListTenants:input_type -> tenantidentity.v1.ListTenantsRequest
	6,  // 9: tenantidentity.v1.IdentityService.CreateUser:input_type -> tenantidentity.v1.CreateUserRequest
	7,  // 10: tenantidentity.v1.IdentityService.Login:input_type -> tenantidentity.v1.LoginRequest
	9,  // 11: tenantidentity.v1.IdentityService.GetUser:input_type -> tenantidentity.v1.GetUserRequest
	10, // 12: tenantidentity.v1.IdentityService.ListUsers:input_type -> tenantidentity.v1.ListUsersRequest
	12, // 13: tenantidentity.v1.IdentityService.IssueServiceToken:input_type -> tenantidentity.v1.IssueServiceTokenRequest
	0,  // 14: tenantidentity.v1.TenantService.CreateTenant:output_type -> tenantidentity.v1.Tenant
	0,  // 15: tenantidentity.v1.TenantService.GetTenant:output_type -> tenantidentity.v1.Tenant
	4,  // 16: tenantidentity.v1.TenantService.ListTenants:output_type -> tenantidentity.v1.ListTenantsResponse
	5,  // 17: tenantidentity.v1.IdentityService.CreateUser:output_type -> tenantidentity.v1.User
	8,  // 18: tenantidentity.v1.IdentityService.Login:output_type -> tenantidentity.v1.LoginResponse
	5,  // 19: tenantidentity.v1.IdentityService.GetUser:output_type -> tenantidentity.v1.User
	11, // 20: tenantidentity.v1.IdentityService.ListUsers:output_type -> tenantidentity.v1.ListUsersResponse
	13, // 21: tenantidentity.v1.IdentityService.IssueServiceToken:output_type -> tenantidentity.v1.IssueServiceTokenResponse
	14, // [14:22] is the sub-list for method output_type
	6,  // [6:14] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_tenant_identity_v1_tenant_identity_proto_init() }
func file_tenant_identity_v1_tenant_identity_proto_init() {
	if File_tenant_identity_v1_tenant_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tenant_identity_v1_tenant_identity_proto_rawDesc), len(file_tenant_identity_v1_tenant_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_tenant_identity_v1_tenant_identity_proto_goTypes,
		DependencyIndexes: file_tenant_identity_v1_tenant_identity_proto_depIdxs,
		MessageInfos:      file_tenant_identity_v1_tenant_identity_proto_msgTypes,
	}.Build()
	File_tenant_identity_v1_tenant_identity_proto = out.File
	file_tenant_identity_v1_tenant_identity_proto_goTypes = nil
	file_tenant_identity_v1_tenant_identity_proto_depIdxs = nil
}
