apiVersion: v1
kind: Service
metadata:
  name: tenant-identity-svc
  namespace: ccaas-dev
  labels:
    app: tenant-identity
spec:
  selector:
    app: tenant-identity
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
